### ISSUE TITLE
Add Support for RSD Currency

### ISSUE THREAD

**Issue by itsmartashub** [RetroMusicPlayer/Paisa#109]
Hello, Hemanth. Does Flutter maybe supports Serbian Dinar (RSD) currency?

**Comment by h4h13** [comment]
Will check and update

**Comment by h4h13** [comment]
Is the code is sr or sr_Latn

**Comment by h4h13** [comment]
Is this the one 
![image](https://user-images.githubusercontent.com/2574895/225355001-d5ab7974-13a8-4939-bc84-a97685b0784f.png)

![image](https://user-images.githubusercontent.com/2574895/225355332-ebe71c50-ceb4-4719-b961-ace24714668c.png)
