### ISSUE TITLE
Bugs found in v3.7.3

### ISSUE THREAD

**Issue by sdnitrogen** [RetroMusicPlayer/Paisa#116]
**Home Tab**

- Transactions timeline is in ascending order instead of descending, which is inconvenient as we want to see the latest transactions on top

- Total balance is completely off. It's way too high of a number than it should be. ( This month's income and expenses are correct )

**Accounts Tab**

- Income and Expenses cards on top have the correct total values but each account cards have wrong total balances just like the home screen, they are way off. Again their this month's income and expenses values are correct.

_Note :_ I updated my app from a previous version, it wasn't a fresh install, if that information helps.

**Comment by Golem642** [comment]
I noted something interesting: when making an expense, the money is correctly removed from the account. However, if we delete that expense, we get some weird results like sometimes it's doubled sometimes it's squared or something it's really weird

**Comment by deavmi** [comment]
Total balance is off.

I literally scored a shit tonne of money and was confused.

Also some accounts are somehow negated which is untrue, they were fully balanced (equal expenditure and equal income) before update (and I didn't transact once)/

**Comment by deavmi** [comment]
Income ans expense at top are correct but accounts and homepage balance are wrong.

So experiencing same issue at the original poster.

**Comment by h4h13** [comment]
All these problems got solved please wait for the update

**Comment by deavmi** [comment]
> All these problems got solved please wait for the update

These calculations wouldn't have changed the actual values stored right? Was it just an in-memory miscalculation?
