### ISSUE TITLE
Add the Egyptian pound EGP (£)

### ISSUE THREAD

**Issue by Bmswad1** [RetroMusicPlayer/Paisa#12]

**Comment by h4h13** [comment]
Is this the one 
![Screenshot_1664695267](https://user-images.githubusercontent.com/2574895/193442850-74248c85-c69f-4797-88f2-7b3dbc9d5cb7.png)

**Comment by h4h13** [comment]
Confirm and close this

**Comment by Bmswad1** [comment]
Yup
It's that one
Thanks 😊
