### ISSUE TITLE
[Feature Request] UNDO Delete Button required! 

### ISSUE THREAD

**Issue by iamMG** [RetroMusicPlayer/Paisa#121]
I accidentally deleted an Account! There is no Undo button! Please add.

**Comment by Lorestan00** [comment]
Agreed. I deleted a category and all my expesjese disappeared

**Comment by h4h13** [comment]
We have dialog prompt is not that not enough haha

**Comment by Lorestan00** [comment]
When deleting a category there is no prompt. It just deleted and all the expenses disappear. Very easy to do. A prompt here woudl be useful

**Comment by Spyy004** [comment]
Is someone working on this issue or can i work on it?

**Comment by Spyy004** [comment]
Also if i want to work on it, do i fork the repo and start working or just clone the repo and cut a new branch and do the work?

**Comment by iamMG** [comment]
> Also if i want to work on it, do i fork the repo and start working or just clone the repo and cut a new branch and do the work?
> 

Yes please work on it! That'd be awesome. Can you create a Pull request?

**Comment by Spyy004** [comment]
Yeah i can. I just wanted to know if i can directly cut a branch from this repo and work on it and then create a PR or do i need to fork the repo and do all this work?

**Comment by Spyy004** [comment]
I have a few doubts. What is the actual requirement?
Do we need a undo delete button once the user has deleted a category/debt/credit or do I need to add a dialog box that confirms the delete of a debt/credit?
The dialog box appears when you try to delete a category but it doesn't appear when u are deleting a debt/credit.

**Comment by Lorestan00** [comment]
Dialog box

**Comment by iamMG** [comment]
> do I need to add a dialog box that confirms the delete of a debt/credit?

I vote for this.

**Comment by Spyy004** [comment]
made the feature. raised a PR. Have a look

**Comment by h4h13** [comment]
> Also if i want to work on it, do i fork the repo and start working or just clone the repo and cut a new branch and do the work?

Fork would be useful

**Comment by h4h13** [comment]
> made the feature. raised a PR. Have a look

Which PR?

**Comment by Spyy004** [comment]
PR to add an alert dialog whenever user taps delete icon on the add debt page

**Comment by h4h13** [comment]
This is about when you delete and user will 5secs to undo the action

**Comment by h4h13** [comment]
We have already confirmation dialog why we need another action it's to much so closing the card
