### ISSUE TITLE
Moroccan Dirham (MAD) not present in currency list

### ISSUE THREAD

**Issue by bahaedin** [RetroMusicPlayer/Paisa#122]
I use the **latest version 3.7.3** 
Changelog says that **Moroccan Dirham (MAD)** is included but i couldn't find it.

![Screenshot_20230318-025219_Paisa](https://user-images.githubusercontent.com/57917164/226080846-f983c105-68ff-474d-a045-fba1fbb21eb2.png)

**Comment by Shabbir260505** [comment]
Currency "MAD" isn't currently supported by flutter, so it is removed.

**Comment by h4h13** [comment]
Yes it's not supported but we have added a custom symbol so you can add your own symbols
