### ISSUE TITLE
Category tab missing

### ISSUE THREAD

**Issue by Lorestan00** [RetroMusicPlayer/Paisa#124]
The category tab is missing on foldables when they are closed

**Comment by Shabbir260505** [comment]
Version of app?

**Comment by Lorestan00** [comment]
Latest one 3.7.3

**Comment by Shabbir260505** [comment]
Please provide screenshot.

**Comment by Lorestan00** [comment]
Here you go. One of the inside screen and one of thr outside screen

**Comment by h4h13** [comment]
Closing this ticket

**Comment by Lorestan00** [comment]
It's still missing in the latest version

**Comment by Lorestan00** [comment]
![Screenshot_20230322_014228_Paisa](https://user-images.githubusercontent.com/81394097/226780534-ff0aacd1-2259-42d9-acac-40e05da32ec7.jpg)
![Screenshot_20230322_014236_Paisa](https://user-images.githubusercontent.com/81394097/226780576-5b20051b-92f1-42e6-89b1-b7a8e398aead.jpg)

**Comment by Lorestan00** [comment]
Here some screenshots to show you
