### ISSUE TITLE
Can not delete transaction because of wrong key has been passed in deleteUseCase().

### ISSUE THREAD

**Issue by zahidshaikh08** [RetroMusicPlayer/Paisa#128]
Currently you can not delete the transaction because instead of passing `currentExpense!.superId` code is passing `currentExpense!.key` and `currentExpense!.key` is **null** so hive is returning an error stating transaction not found in current box something like this.

Got this issue while tracking total balance issue after deleting the account.

By changing to following code deleting transaction started working, but still total balance issue is still there even though my transactions list is empty.

![image](https://user-images.githubusercontent.com/59495361/226171359-b960a7d3-fe2a-43d4-8abf-e3ee497433fa.png)

**Comment by zahidshaikh08** [comment]
One more question why 

`account.amount = (currentExpense!.currency + account.amount!);`

Instead of increasing amount to account's balance we have to delete this transactions amount from actual total account's balance.

So IMO code should be like this...

`account.amount = (account.amount! - currentExpense!.currency);`

**Comment by h4h13** [comment]
This has been taken care of it

**Comment by h4h13** [comment]
Let me know if it's working or not
