### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by ofek150** [RetroMusicPlayer/Paisa#134]
Please add widgets for seeing current balance and entering an expense
Here's an example from another app that I am using:
![IMG_20230321_214638.jpg](https://user-images.githubusercontent.com/45180767/226724062-b56b0091-5ff2-4dd4-93bb-064c465449a2.jpg)

**Comment by Lorestan00** [comment]
What app is that?

**Comment by ofek150** [comment]
[Money manager & expenses](https://play.google.com/store/apps/details?id=ru.innim.my_finance)

**Comment by Lorestan00** [comment]
Thanks
