### ISSUE TITLE
Get currency information from Paisa's own database instead of the intl library

### ISSUE THREAD

**Issue by EzeKoren** [RetroMusicPlayer/Paisa#139]
Currently Paisa has a list of country models, where it could reference any listed country's currency's name, symbol, code, and more. 

https://github.com/RetroMusicPlayer/Paisa/blob/078de31ded9c45574aa3fa605fdd7f71a69c07f3/lib/src/data/currencies/models/country_model.dart#L561-L573

Upon loading up the app for the first time, however, it will use Flutter's `NumberFormat.compactSimpleCurrency()` library (documented [here](https://api.flutter.dev/flutter/intl/NumberFormat/NumberFormat.simpleCurrency.html)), which doesn't contain all the necessary information, nor the information for all the countries supported by Paisa, like for example Argentina (the country I live in and I made the PR for yesterday).

I overlooked this issue when I made my PR, and for that I apologize.

The solution I believe would be the best, would be for the list in `currency-model.dart` to be replaced by the one in `country-model.dart`. That way, not only many more countries would be added, but also it would be easier to add new ones not already present, not to mention streamlining the process of adding new currencies not supported by the built in `NumberFormat` library. This would also open the door to the possibility of letting the user add their own custom currency.

Thank you for taking your time to read this, by opening this PR I hope I can help make this amazing app grow by making it just a little better. Cheers!

**Comment by EzeKoren** [comment]
More info:

https://github.com/RetroMusicPlayer/Paisa/blob/078de31ded9c45574aa3fa605fdd7f71a69c07f3/lib/src/presentation/login/widgets/local_grid_view_widget.dart#L51-L53

When a locale unavailable in the locale list (I.E. Argentina, locale code `es_AR`) is passed onto this function, after failing to find it, the library will try to trim the locale to just the language (in this case es), which works well for languages but not so much for country information and currencies, since it will return completely wrong information.

The problem was reported on my PR #118, as well as PR #104 by @chardinson.

**Comment by h4h13** [comment]
The problem is that thousands of separation and decimal separation

Some countries will have dot separation and some have comma separation

**Comment by EzeKoren** [comment]
That's information already available in the `country_model.dart` file under the `thousands_separator` and `decimal_separator` variables. The first option that comes to mind is to convert the amount of money to a string before displaying it to the user, and replacing both separators with whatever is declared in the country model.

**Comment by h4h13** [comment]
I'm still not know how to use those parameters to custom build currency formatter
