### ISSUE TITLE
app size exploded

### ISSUE THREAD

**Issue by IzzySoft** [RetroMusicPlayer/Paisa#14]
While v1.7.1 came with a size of 23 MB, the following versions jumped over the 70 MB border. Was this planned, or on accident? As the size limit with my repo is at 30 MB, v1.7.1 is the currently last version available there and updates are now disabled. If a smaller APK can be made available, I can pick up again.

**Comment by h4h13** [comment]
if your referring to  GitHub release builds it has debug version please don't follow that, play store will have a properly sized

**Comment by IzzySoft** [comment]
Yes, I'm referring to that. Keep in mind there are users having no access to Google Play. They can instead use an [F-Droid client of their choice](https://android.izzysoft.de/applists/category/named/apps_markets#group_1181), add my repo, and get the APK (including automated updates) [from here](https://apt.izzysoft.de/fdroid/index/apk/dev.hemanths.paisa) – which is picked – tada! – from Github releases automatically (within 24h of your creating a new tag and attaching the APK; currently disabled due to the reasons pointed out). So can you please attach that APK to the releases as well?

**Comment by ShareASmile** [comment]
> Keep in mind there are users having no access to Google Play.

Yes, i have a degoogled phone. I depend mostly on Izzy repositories store for automatic updates when new version is released. So please consider releasing "release" version on github instead of bulky debug builds.

**Comment by ShareASmile** [comment]
@IzzySoft Now Github release builds contain release version instead of debug version, i think Issue is solved now. Waiting for version 
https://github.com/RetroMusicPlayer/Paisa/releases/tag/v2.0.2
 to appear on Izzy repository.

**Comment by IzzySoft** [comment]
Thanks! Auto-updates re-enabled, should show up in about an hour. While on it, I also replaced the icon which you meanwhile changed.

Speaking about metadata changes: mind having [Fastlane structures](https://gitlab.com/-/snippets/1895688) established in your app's repo, so you can take care of those things yourself and control how your app is presented? I could send you the current setup I have here as PR to get you started with that.

**Comment by ShareASmile** [comment]
> Speaking about metadata changes: mind having Fastlane structures established in your app's repo, so you can take care of those things yourself and control how your app is presented?

..maybe you should mention owner of this repository, i think he is not getting notifications from this thread

**Comment by IzzySoft** [comment]
@ShareASmile the owner should always be notified. And while this project is owned by a group (not a single person), @h4h13 as a member of that group is present here :wink: But yes, cannot hurt to show a response from them might be needed, by sending a ping. Hereby done :smile:
