### ISSUE TITLE
Budget tab foldables

### ISSUE THREAD

**Issue by Lorestan00** [RetroMusicPlayer/Paisa#140]
Thr budget tabs on foldables on the main screen doesn't show any figures only the icons and titles. On the external screen it does show figures 

![Screenshot_20230322_014236_Paisa](https://user-images.githubusercontent.com/81394097/226780860-b64b2fe3-5925-4b10-845b-347e57ceddfb.jpg)

![Screenshot_20230322_014228_Paisa](https://user-images.githubusercontent.com/81394097/226780872-8f83603e-ef1e-4085-84e2-599a961d06a8.jpg)

**Comment by h4h13** [comment]
I never knew we have foldable users thank you for using and can you join internal testers

**Comment by h4h13** [comment]
fixed
