### ISSUE TITLE
[Feature Request] Add credit card option in accounts

### ISSUE THREAD

**Issue by W1zardK1ng** [RetroMusicPlayer/Paisa#143]
I could see Cash,Bank and Wallet options under Accounts section, it will be nice to have credit option also to add credit cards and would prefer that the credit card balance can be excluded from the total balance. 
Maybe a toggle to  add or exclude credit card balance to the total balance.

**Comment by h4h13** [comment]
We have credit card before later decided anything card related is bank so you add it as normal bank and track expenses

**Comment by W1zardK1ng** [comment]
okay got your point, in this case can we include a toggle to add or exclude balance of a account in the total balance.

**Comment by h4h13** [comment]
Closing for now
