### ISSUE TITLE
remember sorting mode always

### ISSUE THREAD

**Issue by itsmmt305** [RetroMusicPlayer/Paisa#153]
i was a user of paisa in its initial days. i left using paisa within the first month because the default sorting view was set to daily and i had to set it manually to monthly everytime i switched tabs or reopened the app or made a new entry. i hoped the dev wud do sthing abt it in the updates. cudnt open an issue becz wasnt on github back then. so i kept coming back to check

i only downloaded the app again recently and was glad to see the view does not change when switching tabs. but making a new entry or reopening the app still sets it back to daily

kindly add an option in setting for this or make it so that the default view option is the one chosen by the user earlier. even when adding an expense or closing the app. itll be very handy and helpful.

**Comment by h4h13** [comment]
hi @itsmmt305 this is a good suggestion will do it
