### ISSUE TITLE
[Feature Request] Transit from Local Storage to Cloud Storage. 

### ISSUE THREAD

**Issue by zahidshaikh08** [RetroMusicPlayer/Paisa#154]
I would like to transit current local database to firebase cloudstore.

Because once you uninstall the app all the data is deleted.

Even though we can take backup of our data, currently we can not restore the backup on different devices.

In this case instead of using local database, firebase cloudstore would make more sense.

We can easily authenticate users via Google and store the data at Central place in cloud firestore.

Let me know what do you think of this proposal.

I know this will take sometime for stability but eventually it will be more useful.

Thanks.

**Comment by h4h13** [comment]
This is still a beta app, we have a long way to go
We have branch have implemented Firebase but users are not into sync their expenses into the internet privacy issues
