### ISSUE TITLE
[Feature Request] Add support for Polish characters in expense names

### ISSUE THREAD

**Issue by aaorszulak** [RetroMusicPlayer/Paisa#156]
Currently the default font set here: `lib/src/app.dart:71` (and also in dark theme)
```
      textTheme: GoogleFonts.outfitTextTheme(
        ThemeData.light().textTheme,
      ),
```
doesn't support Polish characters.

<img width="392" alt="Screenshot 2023-03-24 at 22 10 00" src="https://user-images.githubusercontent.com/37516098/227642265-43245678-7c35-49ac-b376-c875cd357230.png">

Would it be possible to change the font?
If not, I could develop a feature that would allow the user to change preferred font.

**Comment by aaorszulak** [comment]
Here I used a classic polish pangram "Zażółć gęślą jaźń"

**Comment by h4h13** [comment]
Yes please do PR will check it out, or you can develop Google font selector

**Comment by h4h13** [comment]
I'm closing this hence you're working on font management
