### ISSUE TITLE
Balances still off

### ISSUE THREAD

**Issue by deavmi** [RetroMusicPlayer/Paisa#159]
My balances for some accounts are still incorrect.

Here are some examples:

![Screenshot_20230325-123025_Paisa.jpg](https://user-images.githubusercontent.com/5207740/227711812-09120882-7ea1-478f-8f3a-7c3de1f66225.jpg)

![Screenshot_20230325-123030_Paisa.jpg](https://user-images.githubusercontent.com/5207740/227711817-297e7c90-6652-4bcc-876a-3ec27a0ca245.jpg)

---

I am on the latest release available from GitHub, please advise on how one can fix this.

**Comment by h4h13** [comment]
Check account inital balance

**Comment by Golem642** [comment]
> Check account inital balance 

Worked for me, somehow there was a weird amount in it

**Comment by deavmi** [comment]
> Check account inital balance

That worked, thanks!
