### ISSUE TITLE
Visual bugs

### ISSUE THREAD

**Issue by Golem642** [RetroMusicPlayer/Paisa#160]
- [x] When adding or removing an expense/revenue, it keeps the previous state until we refresh the main page by changing pages or close the app
Examples :
    - on the main page, i add an expense, when I click on done it puts me back to the main page but nothing changed, I have to switch to another page and come back to the main one for it to refresh itself and show the changes. Or close the app, that works too
    - same goes for deleting something, it doesn't refresh until you do it manually

- [x] When adding or removing an expense, the page where you enters the details of it refresh / reopens when you click on any input text box

- [ ] When editing anything in the app, the placeholder text of the text input boxes overlaps with the existing content when there is an overlay page opening (like when you click to edit an expense, or your bank account)

Suggestions :

- [ ] Make the icons in the main page colored like in the categories page

Will update if i find more

**Comment by h4h13** [comment]
Hey, Can you please check in latest version [v4.0.4](https://github.com/RetroMusicPlayer/Paisa/releases/tag/v4.0.4)

**Comment by Golem642** [comment]
> Hey, Can you please check in latest version [v4.0.4](https://github.com/RetroMusicPlayer/Paisa/releases/tag/v4.0.4)

Updated

**Comment by Golem642** [comment]
> Hey, Can you please check in latest version [v4.0.4](https://github.com/RetroMusicPlayer/Paisa/releases/tag/v4.0.4)

Updated

**Comment by h4h13** [comment]
How did you creates a tasks

**Comment by Golem642** [comment]
> How did you creates a tasks

Just do something like this

\- [ ]

**Comment by Shabbir260505** [comment]
- [ ] Test

**Comment by h4h13** [comment]
@Golem642 Got it closing this issue for now
