### ISSUE TITLE
Contributing guide

### ISSUE THREAD

**Issue by Lenart12** [RetroMusicPlayer/Paisa#162]
Hello I would like to contribute to this project

Is there any guide on what is the prefered IDE, how to get started, code style, etc...

**Comment by h4h13** [comment]
Hey, thank you for considering contributing,  rules are simple. 

Follow clean architecture, SOLID principles that's it Keep it simple and easy PRs

**Comment by pabloscloud** [comment]
you didn't solve the issue.

> how to get started

how do I set this up?

I tried using android studio installed flutter and stuff but I get an error

**Comment by pabloscloud** [comment]
![image](https://user-images.githubusercontent.com/93644977/229360078-0c8e4b88-2331-42e7-ac78-a4ba44222e1f.png)

**Comment by Fantasy-programming** [comment]
Did the same thing to me, i had to specify the flavor in the build settings
