### ISSUE TITLE
Group/Family Option | Feature 

### ISSUE THREAD

**Issue by iDoNtCaRe-69** [RetroMusicPlayer/Paisa#169]
This Is Going To Be A Long One. First Thing First, What Did I Mean By Group Or Family Option? Basic Meaning Of Group Or Family Is Known To Everyone So I'll Skip That. Many Services Provide A Some Kind Of Group Sync Feature Where Those Guys Can Share Their Progress Like In A Team From A Professional Buisness. 

Let's Guess Most Of Your Family Or Friend Circle Live Together & Pretty Much Know How To Handle A Smartphone. In That Case You Will Ask Them To Install Paisa And Request An Invitation From The Family Head Or Group Leader. Then All Of Them Can Share Their Live Update In That Group.

Specific Transactions Can Be Hidden From Others & Only Main Balance, Total Income & Total Expense Will Be Visible To Everyone. Members Can Opt To Share All Transaction Or Just Few It All Comes To Them.

You May Ask Why Implement Something Like This In An Expense Tracker? Group Sharing Is Pretty Common In This Day & Age. Everyone Does That & Let's Say For Example Your Father Is Regularly Asking For A Total Report Of All Your Expenses, Or Maybe You Are A Father & Your Son Is Wasting Money Like Water Without Giving Proper Explanation. In That Case This Feature Comes In Pretty Handy. Use Cases Are Many, For Example A Small Buisness Where Boss Has Mandate The Use Of Paisa App To All Their Employees & Also Update All Expenses That Are Incurring Inside Premises.

**In Summary This Feature Can/Does**,
- Target A Specific Group Of People.
- Not Introduce Cloud Backup. Local Is Still The Best.
- Help The Group Initiator To Keep Track Without Invading Privacy.
- Not Spy On Anyone.
- Be Used To Make A List Of Grocery. For Example Mom Asked For 2 Kilo Potato & Updated It In Group. Then Someone From That Group Bought It & Updated The Total Expense. 
- Also Help Showing Your Debts/Credits That Are Pending.
- Also Help You To Keep Track Of Your OTT Subscription.
- Be Used In Case Of Emergency, Group Creator Can Pin Some Transaction Like A Due Loan, Other Memebers Can Still See It & Maybe Help Him? Lol
- Provide Various Kind Of Use Case Which Is Totally Limited By User.
- Require A Strong Online Protocol (I Have No Idea) For A Safe Online Syncing. This Is Pretty Obviously A Heavy Task & This Might Not Even See The Day Of Light.

**Comment by h4h13** [comment]
Hmm looks like big feature, do you use any app which does this

**Comment by iDoNtCaRe-69** [comment]
No Idea If Any App Have This, Just An Imagination. (Inspired By MS Whiteboard)

**Comment by h4h13** [comment]
Nice but Paisa's aim is to keep it simple it's going out of hand

**Comment by SahSantoshh** [comment]
My app had similar feature, but it's not in play store anymore. Anyway, found this app today. Exploring it to add one
