### ISSUE TITLE
Bugs

### ISSUE THREAD

**Issue by Shabbir260505** [RetroMusicPlayer/Paisa#171]
v4.0.5

1. W̶e̶ c̶a̶n̶n̶o̶t̶ u̶p̶d̶a̶t̶e̶ t̶i̶m̶e̶ o̶f̶ t̶r̶a̶n̶s̶a̶c̶t̶i̶o̶n̶s̶ a̶d̶d̶e̶d̶ b̶e̶f̶o̶r̶e̶ v̶4̶.0̶.5̶.
2. W̶h̶e̶n̶ c̶r̶e̶a̶t̶i̶n̶g̶ a̶ n̶e̶w̶ t̶r̶a̶n̶s̶a̶c̶t̶i̶o̶n̶, i̶t̶ o̶n̶l̶y̶ s̶e̶t̶s̶ t̶h̶e̶ c̶u̶r̶r̶e̶n̶t̶ t̶i̶m̶e̶ e̶v̶e̶n̶ i̶f̶ w̶e̶ c̶h̶a̶n̶g̶e̶ i̶t̶.
3. W̶h̶e̶n̶ e̶d̶i̶t̶i̶n̶g̶ o̶l̶d̶ t̶r̶a̶n̶s̶a̶c̶t̶i̶o̶n̶s̶, i̶t̶ i̶s̶ b̶y̶ d̶e̶f̶a̶u̶l̶t̶ s̶e̶l̶e̶c̶t̶e̶d̶ a̶s̶ e̶x̶p̶e̶n̶s̶e̶ e̶v̶e̶n̶ i̶f̶ i̶t̶ w̶a̶s̶ i̶n̶c̶o̶m̶e̶. W̶h̶i̶c̶h̶ w̶h̶e̶n̶ u̶p̶d̶a̶t̶i̶n̶g̶ w̶i̶l̶l̶ c̶o̶n̶v̶e̶r̶t̶ i̶n̶c̶o̶m̶e̶ i̶n̶t̶o̶ e̶x̶p̶e̶n̶s̶e̶ a̶c̶c̶i̶d̶e̶n̶t̶a̶l̶l̶y̶ i̶f̶ n̶o̶t̶ s̶e̶e̶n̶.
4. Sometimes deleting transactions glitches and freezes the app.
5. The title, "Permanently delete?" in the delete dialogue box is in white colour and hard to see sometimes in light theme.
6. In settings, under accent color, "Dynamic" switch is off by default but dynamic colours are on. Therefore, we need to turn switch on and off once to use inbuilt custom colours in app.

v4.1.1
1. Cannot delete debt by pressing "Delete" in dialogue box. You need to press "Cancel" after "Delete" to make it disappear.

**Comment by h4h13** [comment]
Fixed: The title, "Permanently delete?" in the delete dialogue box is in white colour and hard to see sometimes in light theme.

**Comment by h4h13** [comment]
Fixed: Cannot delete debt by pressing "Delete" in dialogue box. You need to press "Cancel" after "Delete" to make it disappear.

**Comment by h4h13** [comment]
Fixed: In settings, under accent color, "Dynamic" switch is off by default but dynamic colours are on. Therefore, we need to turn switch on and off once to use inbuilt custom colours in app.

**Comment by h4h13** [comment]
Fixed: W̶h̶e̶n̶ e̶d̶i̶t̶i̶n̶g̶ o̶l̶d̶ t̶r̶a̶n̶s̶a̶c̶t̶i̶o̶n̶s̶, i̶t̶ i̶s̶ b̶y̶ d̶e̶f̶a̶u̶l̶t̶ s̶e̶l̶e̶c̶t̶e̶d̶ a̶s̶ e̶x̶p̶e̶n̶s̶e̶ e̶v̶e̶n̶ i̶f̶ i̶t̶ w̶a̶s̶ i̶n̶c̶o̶m̶e̶. W̶h̶i̶c̶h̶ w̶h̶e̶n̶ u̶p̶d̶a̶t̶i̶n̶g̶ w̶i̶l̶l̶ c̶o̶n̶v̶e̶r̶t̶ i̶n̶c̶o̶m̶e̶ i̶n̶t̶o̶ e̶x̶p̶e̶n̶s̶e̶ a̶c̶c̶i̶d̶e̶n̶t̶a̶l̶l̶y̶ i̶f̶ n̶o̶t̶ s̶e̶e̶n̶.

**Comment by h4h13** [comment]
Fixed: W̶h̶e̶n̶ c̶r̶e̶a̶t̶i̶n̶g̶ a̶ n̶e̶w̶ t̶r̶a̶n̶s̶a̶c̶t̶i̶o̶n̶, i̶t̶ o̶n̶l̶y̶ s̶e̶t̶s̶ t̶h̶e̶ c̶u̶r̶r̶e̶n̶t̶ t̶i̶m̶e̶ e̶v̶e̶n̶ i̶f̶ w̶e̶ c̶h̶a̶n̶g̶e̶ i̶t̶.
