### ISSUE TITLE
Resize Plus Button | UI Enhancement 

### ISSUE THREAD

**Issue by iDoNtCaRe-69** [RetroMusicPlayer/Paisa#174]
Plus Icon Always Felt Somewhat **Oddly Big** To Me. For Example New Chat Icon From **Whatsapp** Is Perfectly Small & Doesn't Block The View. 

Most Of The Time It **Blocks Amount** Of Transactions. You Can Also Understand It When There Are Hundreds Of Transactions History & It Becomes Irritating At Some Point.

Another Perfect Example Is **Telegram**.

**Comment by h4h13** [comment]
Hey, we have kept the Floating Action Button big for aesthetic reasons Keeping it small makes just like another
