### ISSUE TITLE
navigationBarColor doesn't follow color of background

### ISSUE THREAD

**Issue by Jean-BaptisteC** [RetroMusicPlayer/Paisa#18]
<img src="https://user-images.githubusercontent.com/87148630/193633064-ab6f5d5d-82dd-4a95-abeb-0cc0e370102e.png" width="500"/>

navigationBarColor Android is dark and background color is beige

Android 13 - Pixel 6
Version v1.8.17

**Comment by h4h13** [comment]
Will check on this
