### ISSUE TITLE
App detects Hungarian system language as Chinese

### ISSUE THREAD

**Issue by d4f5409d** [RetroMusicPlayer/Paisa#181]

**Comment by alba4k** [comment]
Same issue here, with german as default locale

I don't think it's language-depent, half of the app is simply chinese

started noticing this after 4.1.7, still there in 4.2.2

https://linksharing.samsungcloud.com/i2DZrr257TaC

https://linksharing.samsungcloud.com/5b6f1XYE5hm0

**Comment by alba4k** [comment]
( @d4f5409d )

This can be temporarily fixed by setting English as your secondary system language

https://linksharing.samsungcloud.com/jDP9uaIki64m

**Comment by justTOBBI** [comment]
Can confirm the bug. 
System Locale is German and display language is something Asia

**Comment by alba4k** [comment]
Check the workaround I suggested

**Comment by justTOBBI** [comment]
> @justTOBBI check the workaround I suggested

@alba4k I actually can't do that due to Miuis restrictions smh

**Comment by alba4k** [comment]
@justTOBBI damn that sucks

So going into Settings > Additional Settings > Languages and Input > Languages only lets you select a single option? (random article I found online suggested this)

**Comment by justTOBBI** [comment]
Fixed in latest release
