### ISSUE TITLE
This month is showing last year's month details

### ISSUE THREAD

**Issue by MominRaza** [RetroMusicPlayer/Paisa#182]
This month details are wrong as the new month just started and I don't have any record for this month yet, it is using last month details
![Screenshot_20230401-065052.png](https://user-images.githubusercontent.com/42776853/229259703-973f6d05-a41f-4b85-bdb6-bb8c06e89028.png)

![Screenshot_20230401-071245.png](https://user-images.githubusercontent.com/42776853/229259772-a4f3866e-0bf3-4246-b094-b53e5d199e63.png)

Add you can see it's April 2022 details

**Comment by MominRaza** [comment]
You can assign that too me, I will be working on this

**Comment by Shabbir260505** [comment]
It would be great if you could help with this. Please create a pull request.
