### ISSUE TITLE
Category icon state in category edit screen is not persistent

### ISSUE THREAD

**Issue by MominRaza** [RetroMusicPlayer/Paisa#183]
https://user-images.githubusercontent.com/42776853/229259960-50e95fed-1597-4336-96ea-59a1556a3f30.mp4

Category icon state is not persistent, as changing budget or color it is reverting back to default home icon.

**Comment by MominRaza** [comment]
You can assign that too me, I will be working on this

**Comment by Shabbir260505** [comment]
It would be great if you could help with this. Please create a pull request.
