### ISSUE TITLE
Dedicated Linux App | Multi-Platform Support 

### ISSUE THREAD

**Issue by iDoNtCaRe-69** [RetroMusicPlayer/Paisa#194]
Linux Have Millions Of Packaging Formate. For Example Appimage Which Is Literally An Executable File For Linux, AUR Which Is A Community-Driven App Store Or Snap, Flatpak & Many More. I'll Suggest Starting With Appimage As It Can Be Easily Executable & Thanks To It's Portable Formate Anyone Can Store It Anywhere For Offline Use.

**Comment by h4h13** [comment]
I don't Linux to test it you're happy to welcome to add support to it
