### ISSUE TITLE
Multiple Profiles [Feature Request]

### ISSUE THREAD

**Issue by Sab00729** [RetroMusicPlayer/Paisa#197]
An option to add multiple profiles in the app 

For Example : Let's say I'm a businessman and i want to maintain my personal accounts and business accounts seperately without mixing them 

Example 2 : Suppose there are two people who want to maintain their accounts in one device 

![Screenshot_2023-04-03-08-54-20-385_dev hemanths paisa](https://user-images.githubusercontent.com/89871684/229408491-b827d818-c522-4281-aa49-a4df000b46c1.png)

**Comment by h4h13** [comment]
Can't do at the movement.
