### ISSUE TITLE
[UI Change] Move Categories section from home screen

### ISSUE THREAD

**Issue by W1zardK1ng** [RetroMusicPlayer/Paisa#199]
Categories section is not something which we access on daily basis, so it doesn't needs to be there on the home screen.
we can move it to below profile section or somewhere else make home screen of the app much simpler.

**Comment by MominRaza** [comment]
I have other idea about categories, we have to make it more useful, we have to add filter based on category in this tab.
Just same as Accounts tab.

**Comment by h4h13** [comment]
![image](https://user-images.githubusercontent.com/2574895/229716255-c62ce473-c962-41b1-9328-4bc8e487b706.png)

**Comment by MominRaza** [comment]
Okay you moved it to the Drawer, but do we still considering adding filter based on categories?

**Comment by h4h13** [comment]
On search ?
