### ISSUE TITLE
Add Chilean Peso (CLP) currency

### ISSUE THREAD

**Issue by SeerLite** [RetroMusicPlayer/Paisa#200]
Hi!

Could you please add the Chilean Peso (CLP) currency?

It uses the dollar sign and has no decimal units (?). E.g:

$1,000,000

Also, we use a dot instead of a comma for thousands separator, so if possible the above should look like this:

$1.000.000

Thank you!

**Comment by h4h13** [comment]
Need to check this but, this currency is not added for support
