### ISSUE TITLE
[UI Change] Resize/Hide Calender and Plus Icons

### ISSUE THREAD

**Issue by W1zardK1ng** [RetroMusicPlayer/Paisa#202]
Due to the big clender icon in the Overview table and plus (+) icon in the Debts tabs, im unabke to view some values in those sections.
Please resize or hide those icons while we scroll down of the page or just make those tabs behave exactly like how Categories tab is handling it.
Please find the screenshots.

<img width="540" alt="Screenshot_20230403-130430" src="https://user-images.githubusercontent.com/110819956/229555945-6b449325-39fe-467d-ac35-055a6482c522.png">
<img width="540" alt="Screenshot_20230403-130439" src="https://user-images.githubusercontent.com/110819956/229555963-aba89615-116d-4e72-a7b6-40b6e8087c58.png">

**Comment by MominRaza** [comment]
I can confirm this bug.

Solution:
These two tabs just has to be same as home, accounts and category tab. (Space on the last for FAB)

I will work on it.
