### ISSUE TITLE
[BUG] Date/Time not showing correctly on updating an expense

### ISSUE THREAD

**Issue by W1zardK1ng** [RetroMusicPlayer/Paisa#203]
While updating an expense, insted of showing the exisitng date and time the app shows current date and time of the phone.
Please fix this to show the already added date and time while updating an expense

**Comment by MominRaza** [comment]
I can confirm this bug.
And one more bug, the select account is also not showing already selected account as selected.

I'll work on both of these as one fix.

**Comment by MominRaza** [comment]
I can also find the same bug in Debts,
Updating debts or credits also not showing already selected start and end date.

I'll work on that as well

**Comment by MominRaza** [comment]
updating an expense bug is not reproducible in Master, only updating debts is still present.
