### ISSUE TITLE
Add Reminder | Feature Request 

### ISSUE THREAD

**Issue by iDoNtCaRe-69** [RetroMusicPlayer/Paisa#204]
**Reminder** Is Exactly Like An Alarm Which Rings At Or Before The Designated Time. Reminder In Paisa App Should Work In Same Manner. Whenever Someone Sets An Reminder For Particular Transaction, Like A Monthly Subscription, Debt, Budget etc. It Should Go Off Whenever A Specific **Events** Is Triggered.

**What Is Should Do :-**
- Add An _In-App Reminder_ Function Which Should Play A Music When Certain Event Meets The Requirment, Or
- It Should Redirect User To Clock App Whenever **Set Reminder** Button Is Pressed, Or
- It Should Redirect User To Calander App & Open A Reminder/Task Tab.

_P.S.- You Can Take This To A Next Level With Issue #205 ._

**Comment by h4h13** [comment]
Hey, This looks too much for me to implement hence closing it
