### ISSUE TITLE
In-App Notification| Feature Request 

### ISSUE THREAD

**Issue by iDoNtCaRe-69** [RetroMusicPlayer/Paisa#205]
This Is Exactly What It Sounds Like, Most Apps Have Some Kind Of Notification System Which Show's Anything From It's Core Functionality. In This Case It Should Be Something Like Reminders, When Budget Limit Exceeds, When Month Ends, When Year Ends, When It's Time For Monthly Subscription, Etc. 

This Feature Should Get Your Total Attention After Backup & Restore. It's A Very Basic Thing That Fine Tunes The Overall UX. 

_P.S. This Is Continuation Of Issue #204._

**Comment by h4h13** [comment]
This is long way to go implement such things, closing for now
