### ISSUE TITLE
App is in Chinese 

### ISSUE THREAD

**Issue by UltraHQ** [RetroMusicPlayer/Paisa#206]
I don't speak Chinese. But for some reason this app shows in Chinese, and there's no setting to change that.
My system language is German.

**Comment by iDoNtCaRe-69** [comment]
Use English As Your Secondary Language From System Settings, No Need To Change Primary Language. Then Force Stop The App.

**Comment by fleurc** [comment]
@iDoNtCaRe-69 This helped, however this issue shouldn't happen in the first place

**Comment by iDoNtCaRe-69** [comment]
It' Has Been Already Noted, Should Be Fixed Sooner Or Later.

**Comment by h4h13** [comment]
For now we have removed Chinese will be back by fixing
