### ISSUE TITLE
Navigation Button | Bug

### ISSUE THREAD

**Issue by iDoNtCaRe-69** [RetroMusicPlayer/Paisa#207]
Space Where Navigation Button Resides, Is Avoiding The System Default Theme. I'm Using Dark Mode Right Now & It's Showing White. 

![Screenshot_20230404-154519867](https://user-images.githubusercontent.com/59225664/229761632-aa68d663-1c0b-4b42-a8a5-8dc8a06955bc.jpg)

Make It Follow System Theme Instead Of Ignoring It.

**Comment by h4h13** [comment]
Duplicate #79
