### ISSUE TITLE
Debt & Credit | Bug 

### ISSUE THREAD

**Issue by iDoNtCaRe-69** [RetroMusicPlayer/Paisa#212]
Paying Debt From Debt Tab Should Always Deduct Money From Total Remaining Balance. In That Same Manner Credits Should Always Auto Add Balance To The Total Remaining Amount.

**Comment by Miltora** [comment]
Maybe you could select from which account you are paying and the transaction history is showing in the main tab and in the debt/credit tab. Now you have to refresh it two times once in the normal transaction and in the debt/credit tab.
