### ISSUE TITLE
[BUG] Language bug - Chinese(or something else)??

### ISSUE THREAD

**Issue by moinmoinde1** [RetroMusicPlayer/Paisa#213]
Text translated by Google translator (German to English)

 I think I have a bug in the Paisa app.
 I installed the app from this GitHub repo and from the Google Play Store.  Both times switched to Chinese or something after the opening screen, but managed to get a bit further since I used google translate.
 I resetted the Paisa App to show this.

Screen Recording:
![Screen Recording 1](https://user-images.githubusercontent.com/101004641/230416302-3072e23d-2340-409b-8a7f-a952305c2815.mp4)

<details><summary>Details</summary>
<p>

System Language: de_DE (German)
Model Name: Galaxy Tab S7
---Samsung Galaxy Tab S7 FE WiFi 64GB
Model number: SM-T733
OneUI version: 4.1
Android version: 12
Using: Samsung DeX on Device (Tab)

</p>
</details>

**Comment by LeonardoLeoo89** [comment]
Same bug in Italian, everything is in Chinese

**Comment by Frobby01** [comment]
Same here in Italian

**Comment by orl0pl** [comment]
Same here — polish

**Comment by guillecoelho** [comment]
Same here

**Comment by Silas-jufo** [comment]
+1 ---- Germany

**Comment by The-Linux-User** [comment]
Same here - Germany

**Comment by srcarkk** [comment]
Same here - Brazil

**Comment by srcarkk** [comment]
Translated with google translator:

I found a way, just go to the device language and **(if possible)** add the US English language as a second language.
