### ISSUE TITLE
A Better Balance System | Enhancement 

### ISSUE THREAD

**Issue by iDoNtCaRe-69** [RetroMusicPlayer/Paisa#214]
This Is Going To Be Tricky & Also Many Might Hate It. We All Know What Balance Is, It Shows Total **CURRENT** Amount . The Word **CURRENT** Is Subjective & If I Jump To A Particular Date, It Should Display The Current Balance Of That Particular Date.

Here's An Example, Let's Say I Had Like 20 Transactions Last Month. But Now Something Came Up & I Want To Check My Balance Sheet Of December 2022. Then The Overall Scene Should Be Upto That Particular Month/Date Only. It Shouldn't Show Total Balance Of April 2023, Instead It Should Show Everything Untill December 2022.

**Comment by h4h13** [comment]
Hey, you want to see per month transactions ?
