### ISSUE TITLE
Add default categories to get started with

### ISSUE THREAD

**Issue by shbhmnk** [RetroMusicPlayer/Paisa#216]
Add some default categories to get the user started with. Currently there are no categories added for the user at initial point. This makes the for a long on-boarding experience for a new user and could cause as a barrier to use keep using the app.

**Suggestion:** Add some common categories by default such as Income, Food, Groceries, Fuel, etc. Feel free to add more as necessary.

**Comment by Shabbir260505** [comment]
Already in the suggestions list. And you can create categories as per your need at any point.

**Comment by shbhmnk** [comment]
Thanks @Shabbir260505. I was not able to find tracking issue so created this one. Could you please link to the suggestions list. If there is existing issue to track this requirement then we can close this issue. 

> And you can create categories as per your need at any point.

To be clear, I am not pointing at any issues in category creation. This is a suggestion to provide a set of categories at the start to improve UX.

**Comment by Shabbir260505** [comment]
Just to be clear this point outs about a suggestion to pre-add a few categories such as food, travel, fuel, etc. as inbuilt rather than adding manually as a starter like the "Default" category is pre-added.

**Comment by h4h13** [comment]
![image](https://github.com/RetroMusicPlayer/Paisa/assets/2574895/bbebff28-b913-4a76-aa1d-157c87c83daf)
