### ISSUE TITLE
Improved README.md with proper instructions to build the project.

### ISSUE THREAD

**Issue by Akimcx** [RetroMusicPlayer/Paisa#217]
Hey, I really want to contribute to this project, but I've been having a hard time building it for the past two days. Would you guys consider creating a better README.md with proper instructions for building the project? I think it's the least you can do.
Best regards.

**Comment by iDoNtCaRe-69** [comment]
Totally Agreed.

**Comment by Akimcx** [comment]
> Yeah it should be great steps, we can add the contribution guide. It also took me some time but I figured it out with one Google search, but still it's good to have steps.

Could you please give the steps required to build the project. Would be great

**Comment by h4h13** [comment]
Hey you guys want to see how to build app ?

**Comment by MominRaza** [comment]
Yes Add Build steps in Readme file in beside translations steps, as it uses flavor most flutter dev not know about it

**Comment by hugoassisj** [comment]
This is A MUST for any serious OSS willing to have contributors.
