### ISSUE TITLE
[Suggestion] Separate spending by year on monthly view

### ISSUE THREAD

**Issue by skff-err** [RetroMusicPlayer/Paisa#22]
currently on version 1.9.0, if income/expenses of the same month and of different years were to be viewed on the monthly view category, they would show in the same month instead of being separated by years

eg:-

**July**
1 July 2022 - $30
23 July 2009 - $3

_instead of_

**July**
1 July - $30

**July 2009**
23 July - $3

----------------------

this would be misleading to people as they would think that they have gone overbudget due to the way the total spending would be displayed

**Comment by h4h13** [comment]
I'll check this

**Comment by h4h13** [comment]
Hey can you check with latest version
