### ISSUE TITLE
List of bugs in v4.2.2

### ISSUE THREAD

**Issue by h4h13** [RetroMusicPlayer/Paisa#220]
- [x] Decimals in initial amount of accounts not working. 
- [x] Localisation translation of "back-up and restore" page.
- [x] If there are no transactions in the current month, it shows the income and expense amount of last year in the total balance widget.
- [x] Icons of categories get reset to the default home icon if we click the budget switch or set the color of the category.
- [x] The app language is Chinese for some people (Solution is pinned).
- [ ]  Days left in debt/credit is always 0.
- [x] Income chart in the home tab doesn't work.
- [x]  Income chart shows data of the expense chart in the home tab.
- [ ] Some characters when used in custom symbol, it shows "☒".
- [x]  Custom symbols' "Symbol on left" toggle doesn't work.
- [x]  In the Overview tab, there should be empty space at the end of the list because we can't see the data if there are many categories.
- [x]  In Overview, select date range should not select future dates because it shows a grey screen.
- [x]  In overview, if there is no transaction in the selected date range, it shows a grey screen.

**Comment by h4h13** [comment]
This issue to track all posted from telegram till date of 18-04-2023

**Comment by itsAdityaRathore** [comment]
Fixed and created PR for Days left in debt/credit is always 0. @h4h13
