### ISSUE TITLE
UI bug in settings menu

### ISSUE THREAD

**Issue by Spiky-4** [RetroMusicPlayer/Paisa#224]
Both in horizontal and vertical orientation bottom of settings menu does not display correctly when scrolling down.

![Screenshot_20230503-123636](https://user-images.githubusercontent.com/132446558/235895627-e8632348-be7b-4fda-9064-bd0314be5780.png)

![Screenshot_20230503-124449](https://user-images.githubusercontent.com/132446558/235895634-e34af042-965d-4d27-adbe-c1fb34559328.png)

**Comment by itsAdityaRathore** [comment]
@Spiky-4  Can you please elaborate whats not working

**Comment by Spiky-4** [comment]
Can't scroll further in the settings menu than what you can see in the uploaded images.

**Comment by Spiky-4** [comment]
Version 4.6 solved the issue.
