### ISSUE TITLE
[Feature] add language changer in app with Esperanto support

### ISSUE THREAD

**Issue by fleurc** [RetroMusicPlayer/Paisa#226]
Adding a language change feature for the app would be extremely beneficial as several people can then decide their langues. And problems like the language automatically changing to Chinese could be fixed easily.

I also would love to see the language feature support Esperanto, for learning and for those which have native Esperanto.

**Comment by fleurc** [comment]
It's ok, waiting for a feature like this is worth it

**Comment by heuwerk** [comment]
Hello,
sorry to butt in here, but wouldn't it make more sense to use the [app-specific language](https://developer.android.com/guide/topics/resources/app-languages) settings introduced in Android 13 instead of an in-app language switcher?

**Comment by fleurc** [comment]
While the idea is good, not all ROMs with android 13 have this setting available. A lot of incredible android things (like screening calls for an example) are Pixel exclusive.

I'm on Android 13 in my Samsung A73, the setting just doesn't exist for any app, as an example.

**Comment by heuwerk** [comment]
Thanks for your reply. I thought it would be an AOSP feature, as it is available on my GrapheneOS phone.

I can see a list of supported apps under:
Settings -> System -> Languages and input -> App languages

My supported apps:
- Aurora Store
- Simple Calendar
- Droid-ify
- Feeder
- Simple Gallery
- OsmAnd
- Spotify

**Comment by heuwerk** [comment]
Since Paisa uses the system setting for the default language, I don't see a big disadvantage in making the app-specific language available only from Android 13.

All users of an older Android version can still change the system language if they absolutely want to use the app in another language.

**Comment by fleurc** [comment]
Isn't that a little ass-backwards? Changing the entire system language exclusively for 1 app?

**Comment by heuwerk** [comment]
Yeah you could be right.
I just don't know how complicated it would be to include such language picker compared to the android builtin feature.

**Comment by fleurc** [comment]
Yeah, that's the harder to solve bit.

For now, i think implementing the Android 13 built-in thing can work, for older versions leave a section in the options that warns the user of the problems in switching languages for older versions. Examples: Options -> Change Language, clicking Change Language shows a warning saying something like:

"Thanks to the difficulties of implementing a language changer older versions of Android (<13) can only change language based on the system language settings. For Android 13 and upwards, please use the built-in per app language changer."

**Comment by MominRaza** [comment]
Now Paisa supports 10+ languages, I think it is time to implement language switcher, and Android 13 per app language feature.
@h4h13 if you're not already working on it, I can start working on it.

**Comment by h4h13** [comment]
Hey, language changer added will close this
