### ISSUE TITLE
[Feature request] Add widgets

### ISSUE THREAD

**Issue by CortlandNation9** [RetroMusicPlayer/Paisa#233]
Add widgets with quick actions so you can add a new transaction from home screen.

**Comment by h4h13** [comment]
Hey, flutter is not yet capable of creating a Home screen widget, for now, App shorts are added. when it comes will be the first one to add 
![image](https://github.com/RetroMusicPlayer/Paisa/assets/2574895/aa74d06f-0ebe-4bea-babc-7e4c29cd44d7)
