### ISSUE TITLE
Remember selected accounts when updating a Transfer expense

### ISSUE THREAD

**Issue by ticklemyIP** [RetroMusicPlayer/Paisa#239]
If trying to edit a transfer expense the From and To accounts doesn't stay selected on the original ones. Meaning if `A` account is default and I transferred funds from `B` to `A`, then instead of showing the same selection when updating it shows `A` to `B`.
May be related to #238

**Comment by h4h13** [comment]
Hey, the code has been updated to handle the default, and while updated account will be selected
