### ISSUE TITLE
FAB is large

### ISSUE THREAD

**Issue by xmha97** [RetroMusicPlayer/Paisa#24]
Hi,
The FAB is large.

![Screenshot_2022-11-28-11-19-17-703_dev.hemanths.paisa.jpg](https://user-images.githubusercontent.com/23485114/204222347-fa61cfc6-a930-44c9-80a0-87e1ad1c3abc.jpg)

Please fix this issue.
Thanks.

**Comment by h4h13** [comment]
This is asthtics of the app
