### ISSUE TITLE
[Feature Request]
1) Please make accounts vertical aligned instead of horizontal. 
2) Remove that background of accounts card or make account card opacity bit more lesser so that background effect doesn't disturb user.

### ISSUE THREAD

**Issue by mschahar** [RetroMusicPlayer/Paisa#241]
Here that bubble like background is distracting too much.
And swiping horizontally is headache for persons like ne who have 30+ accounts and cards Coz for last card I'll have to swipe too much.

![Screenshot_20230517_192218_Paisa.jpg](https://github.com/RetroMusicPlayer/Paisa/assets/85066622/418f491a-9b64-4fcc-ac55-fc8b62feb04f)

**Comment by h4h13** [comment]
This is done wait for upcoming updates 
![image](https://github.com/RetroMusicPlayer/Paisa/assets/2574895/f0521bb3-76cc-4231-be92-8e9978da1fef)
