### ISSUE TITLE
Glitch when debt amount is set to 0

### ISSUE THREAD

**Issue by Findirfin** [RetroMusicPlayer/Paisa#245]
When the debt a out is set to 0, a infinitely tall light gray box appears inside the debt.

**Comment by h4h13** [comment]
Any screen shot or video would be helpful

**Comment by KiruPoruno** [comment]
Assuming this was never actually fixed, and simply closed due to inactivity, here's a screenshot, taken in version `4.8.1`:

<details>
<summary>Screenshot</summary>
<img src="https://github.com/RetroMusicPlayer/Paisa/assets/55784724/aeb387eb-98a8-4637-b091-26d6c1162f83">
</details>

**Comment by ezzyshabbir05** [comment]
#353, No. 12
