### ISSUE TITLE
Unable to import edited JSON files

### ISSUE THREAD

**Issue by santorfo** [RetroMusicPlayer/Paisa#248]
I wanted to transition from a different payment tracking app to Paisa and I waited until the Import/Backup feature was added to try and produce my own JSON file with the data from my old app based on the format that Paisa produced so that I could import it into Paisa.

I've made sure to keep the formatting and naming the same but no matter what I do, Paisa just doesn't import it. There's no snackbar message claiming errors or anything either. I can import backups generated with Paisa but not my custom one.

I also tried making a backup from Paisa and then only changing the value of an expense and trying to reimport that to test if that works, and it does import but the value I changed in the JSON file stays the same as it was before, which makes no sense.

I've checked json file encoding too in case Paisa was rejecting it because of that. Is it expecting a specific naming scheme for the json filename?

Is what I'm trying to do even possible?

**Comment by h4h13** [comment]
Hey, can you send a sample single entry JSON to check, you must be missing the account ID and Category ID

**Comment by santorfo** [comment]
Sure, here is an example of an expense:

`{"name": "Barbeiro", "currency": 11.0, "time": "2023-04-26T00:00:00.000000", "type": "expense", "accountId": 1, "categoryId": 7, "superId": 80, "description": null, "fromAccountId": null, "toAccountId": null, "transferAmount": 0}`

**Comment by santorfo** [comment]
Hey, been a while, any ideas as to why this didn't work?
