### ISSUE TITLE
F-Droid

### ISSUE THREAD

**Issue by xmha97** [RetroMusicPlayer/Paisa#25]
Please add this app to the F-Droid

**Comment by ExperiencersInternational** [comment]
It's on the IzzyOnDroid repo, all you need to do is add it to your repositories in the app.

![Screenshot_2022-12-05-17-38-42-285_com machiav3lli fdroid](https://user-images.githubusercontent.com/56035537/205704898-28d0c266-2bec-4e3f-b284-a8dadb5d8575.jpg)

**Comment by xmha97** [comment]
Yes, that's right, but I wanted the app to be added to the main repository.

**Comment by h4h13** [comment]
We're not official added to F-droid or any other platforms

**Comment by projjalm** [comment]
Why are you guys not adding it to F-Droid main? Is there any specific reason?

**Comment by ExperiencersInternational** [comment]
@projjalm based what I have heard with other apps, F-Droid has a strict policy on apps in its store
