### ISSUE TITLE
Transfer transaction category don't appear in app

### ISSUE THREAD

**Issue by daaniikusnanta** [RetroMusicPlayer/Paisa#259]
Right now, if you want to move balance between accounts, one has to make an expense from the source and income to the destination. This takes so much work for a simple task. 

The transfered amount also shows in expenses statistics, which  IMO should not. 

Maybe also add the option to add Transfer administration fee, and we can count only that as expense from the source account.

**Comment by daaniikusnanta** [comment]
Ok, so i just found out that Paisa has an home screen action called Transfer. It did what i describe above. But i think it doesn't appear in the app. 

When the action is clicked, it opens the transaction screen with Income and Expense pills on the top. I think it supposed to also have a Transfer pill.

**Comment by h4h13** [comment]
Transfer is something happened in account 
Either bank to cash or vise versa but transaction happened
