### ISSUE TITLE
[Feature] Add more currency options

### ISSUE THREAD

**Issue by ExperiencersInternational** [RetroMusicPlayer/Paisa#26]
Right now, for currency options, this app is pretty lacking.

There's quite a few that are missing, but since I reside in the UK, I really need the ability to be able to use GBP instead of something else.

![Screenshot_2022-12-05-17-41-52-750_dev hemanths paisa](https://user-images.githubusercontent.com/56035537/205705682-27eca350-ecc4-4ec0-8688-4f054e15c49a.png)

**Comment by h4h13** [comment]
We're adding based user requested currencies
