### ISSUE TITLE
Peruvian nuevo sol currency support

### ISSUE THREAD

**Issue by jSanR** [RetroMusicPlayer/Paisa#261]
Hi, I also use retro music player and today I discovered this app! I would love to use it but it currently does not seem to support peruvian nuevo sol (PEN) as a currency.

**Comment by Franz1241** [comment]
You could use Argetinan Pesos and add a "Custom Symbol" to it so it displays the "S/." correctly! :)

**Comment by jSanR** [comment]
Oh, I didn't know I could do that, thanks! Is there any downside of that approach? Exchange rates, for example.
