### ISSUE TITLE
option to exlude accounts from total balance.

### ISSUE THREAD

**Issue by W1zardK1ng** [RetroMusicPlayer/Paisa#267]
I have few accounts which i use to save my emergency funds, etc. I don't want these balance to showed up in the total balance on the main screen.
It will be nice to have an option as exclude from total balance while setting up an bank account or while updating the account.

**Comment by halshar** [comment]
agree, please work on this feature whenever you get the chance

**Comment by ajay-ca** [comment]
I have toggled on the Exclude account option but it still shows up in the total balance section.

![Screenshot_20240423-124315](https://github.com/RetroMusicPlayer/Paisa/assets/87013178/657301bb-4dd5-41d8-877e-448973fdb15a)
![Screenshot_20240423-124520](https://github.com/RetroMusicPlayer/Paisa/assets/87013178/b074bfe5-2bc5-43c0-8f3f-2507ca3a0365)

**App Version**: v6.0.6
**Device**: Nothing Phone (2)
**Android version**: 14
