### ISSUE TITLE
[Feature] add Iraqi Dinar 

### ISSUE THREAD

**Issue by MohamadBayz** [RetroMusicPlayer/Paisa#27]

**Comment by h4h13** [comment]
This is not available in flutter can you tell other currency which works for it

**Comment by MohamadBayz** [comment]
I meant iraqi dinar, and what does you mean by it's not available in flutter, court you please explain?

**Comment by MohamadBayz** [comment]
Oh, then please add this to a todo list so you can add it when they add it to there library

**Comment by h4h13** [comment]
Can you tell more about this currency like code and other things

**Comment by h4h13** [comment]
Closing this issue as of not flutter doesn't support this currency

**Comment by MuhammadBayiz** [comment]
Request for adding Iraqi Dinar,
Reopening it since Iraqi Dinar has been added to [currency_picker](https://pub.dev/packages/currency_picker/changelog) package since `version 2.0.17`

**Comment by MuhammadBayiz** [comment]
Any updates on this?
