### ISSUE TITLE
Support for transaction auto-entry from transactional messages  | Feature Request

### ISSUE THREAD

**Issue by dhamodaran-pandiyan** [RetroMusicPlayer/Paisa#272]
I really really like this app for its clean UI and openness. However, I have noticed one particular aspect that has been quite tedious, which can be improved by other means. i.e.,  the manual entry of money spent transactions. 

It would be fantastic if the app could automate this process by reading transactional SMS messages from the user's mobile device and inferring the transaction details to add as entries in the app. Of course, privacy is of utmost importance, so it would be essential to ensure that the app only accesses and analyzes transactional SMS messages while avoiding any personal or sensitive SMS content. 

This feature would greatly enhance the app's convenience and streamline the user experience, allowing for effortless financial management. 

Few examples: (from which I personally used ones) 

https://play.google.com/store/apps/details?id=com.microsoft.android.smsorganizer
https://play.google.com/store/apps/details?id=com.daamitt.walnut.app     -  Money management tab in this app

**Comment by h4h13** [comment]
duplicate( #246 )
