### ISSUE TITLE
Total balance not the same as account balance

### ISSUE THREAD

**Issue by NC-Evo** [RetroMusicPlayer/Paisa#279]
I only have one account, but the total balance is different from that one. Why is that?

![Screenshot_20230714_034910_Paisa](https://github.com/RetroMusicPlayer/Paisa/assets/69123734/f9e34aaa-c0d9-4b0b-9d9a-0b142f5d9457)
![Screenshot_20230714_034914_Paisa](https://github.com/RetroMusicPlayer/Paisa/assets/69123734/47770308-3036-4f8e-9404-1007a928f37b)

**Comment by h4h13** [comment]
Hey, have you ever added transfer transactions

**Comment by NC-Evo** [comment]
I don't think so. I have a category called Transfer, but I use it to keep track of when I transfer money from my credit card to other people.

**Comment by NC-Evo** [comment]
No, I have never used transfer transactions since I have only one account.

![Screenshot_20230717_051517_Paisa](https://github.com/RetroMusicPlayer/Paisa/assets/69123734/ce64d36a-77a8-4a12-bfa8-2bf2d0ecb648)

**Comment by NC-Evo** [comment]
My initial balance is 0. I tried moving every single tranzaction to another account and deleting the first one, but the total balance is still bugged.

![Screenshot_20230717_063834_Gallery](https://github.com/RetroMusicPlayer/Paisa/assets/69123734/5648f08b-4b59-4739-a1d4-aae9e1ae9b73)

**Comment by h4h13** [comment]
Hey, closing this reopen it if it's not fixed
