### ISSUE TITLE
Amount numbers can overflow and underflow

### ISSUE THREAD

**Issue by KiruPoruno** [RetroMusicPlayer/Paisa#282]
I discovered that numbers seems to wrap around when going below `0.000001`, so `0.0000001` = `1e-7` and `0.0000009` = `9e-7`, and I'd think the same thing would happen if the number gets too big, so you may want to consider adding a ceiling and floor to the size of the number, to prevent this.

**Comment by GabrielDTB** [comment]
The described behavior isn't overflow/underflow at all, it's scientific notation for very small numbers.

**Comment by h4h13** [comment]
Hey, this is internal behaviour of number system don't have control it

**Comment by GabrielDTB** [comment]
From what I understand about your code, not having control of the number system isn't true at all.

I believe you use `toString` to convert the amounts which are stored as doubles to a string to present to the user. If you decided it was worthwhile, you could use `toStringAsFixed` with a fixed number of decimal places that the application accepts.

Or you could use `toStringAsFixed` with the largest amount of decimal places you would want the application to display (10 or something) and trim the trailing zeros after.

Perhaps scientific notation is best, though.
