### ISSUE TITLE
Sensitive Data Masking

### ISSUE THREAD

**Issue by hugoassisj** [RetroMusicPlayer/Paisa#288]
It is very common for banking apps to have a toggle that masks the sensitive data on all screens. Also there is configurable option defining if the masking is enabled upon login. 

This is very helpful to avoid embarrassments when opening the app next to other people.

In Paisa I see this being useful to mask the Total Balance, Incomes and Expenses and Account Totals.

Example:
![IMG_20230718_142821](https://github.com/RetroMusicPlayer/Paisa/assets/45035051/502f2de1-b485-43af-a3bb-9e3d1f7fcaf5)

**Comment by MegPredator** [comment]
Yeah this would be pretty useful

**Comment by h4h13** [comment]
Hey, I don't think it's useful for most and this is not a banking app to have such security
