### ISSUE TITLE
People that owe you money

### ISSUE THREAD

**Issue by TimSousa1** [RetroMusicPlayer/Paisa#293]
It would be awesome if there was a way to keep track of the money people owe you, kinda like the debt tab, but the other way around

**Comment by h4h13** [comment]
We have debit and credit

**Comment by h4h13** [comment]
![image](https://github.com/RetroMusicPlayer/Paisa/assets/2574895/c29cac99-78d6-4dfe-a771-67ac0ad6fa32)
