### ISSUE TITLE
Default Expense/Income name based on the Category | Enhancement

### ISSUE THREAD

**Issue by rnd195** [RetroMusicPlayer/Paisa#298]
As far as I understand, it is mandatory to fill in `Expense/Income name` and select the `Category` of every transaction. 

However, I think that there are times when the name of the category sufficiently explains the transaction (e.g., groceries). It would therefore be handy to default to the name of the `Category` as the `Expense/Income name` once the category is selected.

**Comment by h4h13** [comment]
Hey, this has been added hence closing it
