### ISSUE TITLE
local_auth_api -> update (local_auth 2.1.0)

### ISSUE THREAD

**Issue by Nak9009** [RetroMusicPlayer/Paisa#3]
import 'package:flutter/services.dart';
import 'package:local_auth/local_auth.dart';
import 'package:local_auth_android/local_auth_android.dart';
import 'package:local_auth_ios/local_auth_ios.dart';

class LocalAuthApi {
  final _auth = LocalAuthentication();

  Future<bool> hasBiometrics() async {
    try {
      return _auth.canCheckBiometrics;
    } on PlatformException catch (_) {
      return false;
    }
  }

  Future<bool> authenticate() async {
    final isAvaliable = await hasBiometrics();
    if (!isAvaliable) return false;
    try {
      return _auth.authenticate(
        localizedReason: 'Scan',
        options: const AuthenticationOptions(
          biometricOnly: true,
          useErrorDialogs: true,
          stickyAuth: true),
        authMessages: const <AuthMessages>[
          AndroidAuthMessages(
            signInTitle: "Authenticate for Login",
            cancelButton: 'Cancel',
            goToSettingsButton: 'Settings',
            goToSettingsDescription: 'Please register your Fingerprint',
          ),
          IOSAuthMessages(
            cancelButton: 'Cancel',
          ),
        ]
      );
    } on PlatformException catch (_) {
      return false;
    }
  }
}

**Comment by h4h13** [comment]
We no longer use local auth closing this

**Comment by Nak9009** [comment]
okay. thank you
