### ISSUE TITLE
Unable to update Debt/Credit

### ISSUE THREAD

**Issue by adarsh1001** [RetroMusicPlayer/Paisa#300]
Steps to reproduce:
1. Add a Debt of some amount and save.
2. Open the debt, change the amount and hit update.
3. The update action is unresponsive.

https://github.com/RetroMusicPlayer/Paisa/assets/8820038/f8f4e6f0-1727-480c-9246-e937d765008d

Other Details:
App Version: v4.9.0
Android Version: 13

**Comment by h4h13** [comment]
Hey, Is this fixed closing for now

**Comment by adarsh1001** [comment]
Hi @h4h13, this is not working in v5.0.0-1 as well 🤔
