### ISSUE TITLE
Transactions tab ordered from oldest to most recent

### ISSUE THREAD

**Issue by PICKLERICK2005** [RetroMusicPlayer/Paisa#303]
The transactions are now sorted from old to new after the update rather than from new to old so I have to scroll all the way down to see recent transactions.

![Screenshot_2023-08-01-12-43-17-027_dev.hemanths.paisa-edit.jpg](https://github.com/RetroMusicPlayer/Paisa/assets/81990968/3a7829f2-e42d-4f8c-9458-d460f430f205)

The same goes for the overview tab, the months used to be in descending order (from new to old) and now they're in ascending order, I don't know if this was intended but it's really impractical and it would make more sense if you were to see the most recent transactions first rather than the oldest ones.

![IMG_20230801_124642.jpg](https://github.com/RetroMusicPlayer/Paisa/assets/81990968/6a76c3af-4a8d-4d1d-81d8-ccf413547750)

I'm sorry if this was intended and not a bug, and if it was I'd suggest an option to switch the order between ascending and descending in the filter tab and such.
Thanks for the hard work that was put into this awesome app by anyone who ever happened to do a commit. <3

**Comment by poly000** [comment]
for an example of design: tap to select, then tap the same option to switch between upscend and descend order.
