### ISSUE TITLE
Database got corrupted while importing

### ISSUE THREAD

**Issue by soumyaDghosh** [RetroMusicPlayer/Paisa#304]
I had taken a backup of my transactions to reset the app, because on Monday when I was updating my expenses for Sunday, it didn't showed up in the list but the money was deducted from my cash account. But, then when I restored the backup, it completely messed the descriptions as I have written them in Bengali.

![Screenshot_২০২৩-০৮-০১-২২-২৯-১৭-৩০৬_dev hemanths paisa](https://github.com/RetroMusicPlayer/Paisa/assets/72045785/c056c94d-09c9-457d-b239-20948008eb22)

Also I would try to translate the app in bengali.

EDIT: Android 9 MIUI

**Comment by h4h13** [comment]
Hey, this might local encoded issue, reopen it if it's still there
