### ISSUE TITLE
The "Restore" button doesn't work

### ISSUE THREAD

**Issue by zachvlat** [RetroMusicPlayer/Paisa#31]
Pretty much the title, i m on A13.3, Paisa v2.0.2. Should I roll back to a previous version to get my restore functionality back? (If I remember correctly it used to work...)

**Comment by h4h13** [comment]
We're finding a best solution to store and restore the back-up not yet finished one this

**Comment by zachvlat** [comment]
Is this done? Because I can't find it on the app...
