### ISSUE TITLE
Feature: PSD2 Sync

### ISSUE THREAD

**Issue by ayykamp** [RetroMusicPlayer/Paisa#312]
Add feature to sync with PSD2 api that most european banks use. The [STET PSD2 API ](https://www.stet.eu/en/psd2/)describes several operations that can be realized on user bank accounts, and among others there is AISP (Account Information Service Providers) that allows access to users account transactions

**Comment by h4h13** [comment]
This is the pure offline app we don't communicate or read anything from mobile
