### ISSUE TITLE
<Feature Request>: Preserve Transaction Form Data When Navigating Back

### ISSUE THREAD

**Issue by abhiraj-ku** [RetroMusicPlayer/Paisa#320]
Problem: Currently, navigating back while entering transaction details erases all filled data, causing inconvenience

Solution: Implement a mechanism to save form data locally. Upon returning, users should find their previous details pre-filled, enhancing user experience.

Steps:

Store form data locally when starting a transaction.
Restore saved data when users access the form.
offer the option to resume from saved data.
Auto-save drafts periodically for uninterrupted progress.

Expected Outcome:

Enhanced user experience by preventing data loss, allowing seamless transaction data entry even after accidental navigation.

**Comment by h4h13** [comment]
Hey, This seems overwhelming for me to implement
