### ISSUE TITLE
Feature Request: Add ability to reorder accounts

### ISSUE THREAD

**Issue by Celtaa** [RetroMusicPlayer/Paisa#323]
**Current Behavior**

The app allows users to view their accounts in a vertical or horizontal list. However, users cannot reorder the accounts in either list.

**Proposed Behavior**

The proposed behaviour would allow users to reorder the accounts in both the vertical and horizontal lists. This would allow users to organize their accounts in a way that is most logical and convenient for them.

Thank you for your time and consideration.

**Comment by ezzyshabbir05** [comment]
#353, No. 10
