### ISSUE TITLE
Installation problem 

### ISSUE THREAD

**Issue by Samyak-Bumb** [RetroMusicPlayer/Paisa#329]
![Screenshot_2023-09-17-12-14-55-28_3d73e98b1ad3bd2575f7a56513d89a0c](https://github.com/RetroMusicPlayer/Paisa/assets/88429776/1c409811-dde5-441d-8885-1511ff050024)

I was installing latest version 5 & got this msg

**Comment by h4h13** [comment]
You cannot install play store app to GitHub APK
