### ISSUE TITLE
Bug: name question on first run appears for no reason

### ISSUE THREAD

**Issue by fofajardo** [RetroMusicPlayer/Paisa#332]
I've been using this app for a month now and was suddenly asked to enter my name and to choose to add from the default categories.

I do remember seeing these prompts being shown on first run or when the app was newly installed. Fortunately, there was no data loss, and it was fairly harmless. It did motivate and remind me to backup my data though.

**Comment by h4h13** [comment]
hey if you have missed any steps it would do that pls check which build you have used

**Comment by fofajardo** [comment]
I was on v4.9.2 when the pop-up reappeared - but I've already updated to v5.0.0. Will let you know if it shows up again. Thanks!
