### ISSUE TITLE
Feature Request: Add support for Bikram Sambat (nepali date)

### ISSUE THREAD

**Issue by theleanbow** [RetroMusicPlayer/Paisa#333]
Could you please add support for nepali date (Bikram Sambat) in the app?
Thanks

**Comment by h4h13** [comment]
hey, please add currency if missing at this location like this 
`lib/features/country_picker/data/data_source/local_country_data.dart`


`{
    "code": "HNL",
    "name": "Honduran Lempira",
    "symbol": "L",
    "flag": "HNL",
    "decimal_digits": 2,
    "number": 340,
    "name_plural": "Honduran Lempiras",
    "thousands_separator": ",",
    "decimal_separator": ".",
    "space_between_amount_and_symbol": true,
    "symbol_on_left": true,
    "pattern": "#,##0.00",
  }`

**Comment by h4h13** [comment]
Let me know once that's done or give me relevant information i'll add

**Comment by h4h13** [comment]
Wait is this the currency
