### ISSUE TITLE
Cloud backup through Proton Drive

### ISSUE THREAD

**Issue by SohailKaAccount** [RetroMusicPlayer/Paisa#338]
Backup through Proton Drive should be introduced.

**Comment by Unkn8wn69** [comment]
I think automatic synchronizing to an file on disk is already enough. 
Then you will be able to automatically upload and sync that to any cloud

**Comment by SohailKaAccount** [comment]
Well, currently Proton Drive does not allow automatic file/folder syncing, I believe.

**Comment by Unkn8wn69** [comment]
> Well, currently Proton Drive does not allow automatic file/folder syncing, I believe.

Then that's a feature they should kick out soon. I think making an integration for any kind of cloud drive would be too much of a mess and work to keep maintained.
