### ISSUE TITLE
Language Setting Not Reflecting App Language Properly

### ISSUE THREAD

**Issue by shmps40802** [RetroMusicPlayer/Paisa#343]
When I select Traditional Chinese as the app language within the application, the language inside the app does not correctly switch to Traditional Chinese. Instead, it displays another language that looks like Russian.

![Screenshot_20231005_130335_Paisa](https://github.com/RetroMusicPlayer/Paisa/assets/118676150/20f9ac3a-92a2-4983-9996-df8ad6b1861c)

app version: v5.0.0-1

**Comment by h4h13** [comment]
Hey, fixed the app language changer need to test it well with users
