### ISSUE TITLE
Feature request: allow us to sort transactions from new to old

### ISSUE THREAD

**Issue by quarkl8** [RetroMusicPlayer/Paisa#346]
Title explains it all. It used to work like this until maybe a month or two ago, and it's a pain in the ass to see useless old transactions and have to scroll all the way down to see my latest transactions. It's an unfortunate mar on an otherwise really good and useful app that I hope can be rectified. At least give us the option to sort. Thanks!

**Comment by ezzyshabbir05** [comment]
Added in list, closing.
