### ISSUE TITLE
Request: Add Honduran Lempira Currency (HNL)

### ISSUE THREAD

**Issue by FrankR-7** [RetroMusicPlayer/Paisa#356]
Please add the Honduran Lempira as a usable currency in the app. Its code is **HNL** and it doesn't have a specific sign, it's usually **HNL** 123.45, **Lps** 123.45 or **L.** 123.45. Thanks! Suggested label: Currency

**Comment by konairell** [comment]
I have submitted a Pull request with the added currency! The official currency symbol is L (source: BCH)

**Comment by h4h13** [comment]
Hey, merged PR #358
