### ISSUE TITLE
Unicode data is restored incorrectly from a backup

### ISSUE THREAD

**Issue by sigasigasiga** [RetroMusicPlayer/Paisa#361]
I had a few transactions whose names and descriptions are written in Cyrillic. When I restored them, I got garbage instead of the original inscriptions

**Comment by HenryWu01** [comment]
Same here, all my transaction's name were written in Chinese. Export function seems fine, however when I reimport it to Paisa, I got all srambled, garbarge text.

**Comment by h4h13** [comment]
Hey can you guys give some example

**Comment by HenryWu01** [comment]
> Hey can you guys give some example JSON to test it out

Sure. I have perform a fresh install of Paisa, added some transactions, categories and account to test it out. 
Here is the exported json backup file: [3_paisa_backup.json](https://github.com/RetroMusicPlayer/Paisa/files/13390968/3_paisa_backup.json)
 
I have noticed that the transactions on the account page is all gray blank space, while home page display it successfully. Also, Setting account as default / exclude account and re-enter the account settings, default account and exclude account were still not checked. Seems like these two options were not applied nor saved.

Expected Chinese characters should shown as below:
![Screenshot_20231117_191241_Paisa](https://github.com/RetroMusicPlayer/Paisa/assets/99880210/6033e50b-1c2d-4b3b-812d-b980a0dd5118)
![Screenshot_20231117_191248_Paisa](https://github.com/RetroMusicPlayer/Paisa/assets/99880210/79bd2f28-34cf-4e55-bf93-e9bb15bca9ed)
![Screenshot_20231117_191253_Paisa](https://github.com/RetroMusicPlayer/Paisa/assets/99880210/4cda4214-82d7-40cb-b484-c271f7229218)
![Screenshot_20231117_191257_Paisa](https://github.com/RetroMusicPlayer/Paisa/assets/99880210/4fed002e-d50b-43ea-8930-dc15f27d9eb4)
![Screenshot_20231117_191259_Paisa](https://github.com/RetroMusicPlayer/Paisa/assets/99880210/54a20508-7fbc-43cc-b547-4d7d55bffc26)

**Comment by nitin2953** [comment]
I have some transactions written in Devanagari,
backup file is exporting with unknown characters,
I'm not even able to import the backup file.
![image](https://github.com/RetroMusicPlayer/Paisa/assets/34852979/55861681-4113-482a-b324-1384e7d5d537)

**Comment by h4h13** [comment]
Thanks for the PR works
