### ISSUE TITLE
wrong APKs attached to releases since v4.9.3?

### ISSUE THREAD

**Issue by IzzySoft** [RetroMusicPlayer/Paisa#362]
APKs at all releases starting with 4.9.2 identify as 4.9.2:

    package: name='dev.hemanths.paisa' versionCode='492' versionName='4.9.2'

Are you sure you attached the correct files? Your [`pubspec.yml`](https://github.com/RetroMusicPlayer/Paisa/blob/master/pubspec.yaml#L6) says `version: 5.0.0+500`, so at least v5.0.0 should be correct – but isn't. Can you please check? Thanks in advance!

**Comment by h4h13** [comment]
Hey, sorry was working on automation didn't know how to test it without publishing in releases

**Comment by IzzySoft** [comment]
So will you add the correct one manually then?
