### ISSUE TITLE
Feature Request: Chatbot for tracking expense

### ISSUE THREAD

**Issue by Skyhawk1207** [RetroMusicPlayer/Paisa#363]
Hey!

This app is really awesome, and I use it a lot. Only thing that comes in my way of tracking my expenses at times is the need to open the app, enter the title, select the category, yada yada. If there was a chatbot kind of a thing which could track the expenses based on my message like "350 for Swiggy food" tracks it to food category with Swiggy as a title and 350 as the amount, that would be really great. Thanks!

**Comment by h4h13** [comment]
It's similar to reading the incoming SMS #246
