### ISSUE TITLE
[Feature Request] API (URI Scheme) for adding bills to Paisa

### ISSUE THREAD

**Issue by HenryWu01** [RetroMusicPlayer/Paisa#364]
As a user, I would like an API for adding bills, enabling “Paisa” to bypass the need for in-app support for automatic bill recording. Third-party applications can take on the responsibility of implementing methods to extract bill information from payment apps, either through reading or OCR, and subsequently calling the “Paisa” API to add the extracted information to the bills. This approach would facilitate “automated” bill recording.

I believe the most suitable method for this purpose would be to implement a URI scheme. Since this feature is exclusively for adding records, there are no significant concerns regarding data leakage. “Paisa” can enhance security and control by implementing measures such as “API keys”, “rate limiting”, and an “application allow list” to thwart any potential malicious software or behaviors.

A popular app in China named “钱迹” (Qianji) already offers a feature like this.

Below is a sample URI scheme:
```
paisa://addbill?type=0&amount=123.4&account=Account&category=Category&subcategory=Subcategory&time=2023-10-29T00:00:00Z&remark=Sample
```

|    Name     |                  Description                   |
| :---------: | :--------------------------------------------: |
|    type     | Type of transaction (e.g., expense, income, transfer, etc.) |
|   amount    |             Transaction amount                  |
|   account   |                  Account book                   |
|  category   |                Transaction category             |
| subcategory | Transaction subcategory (I hope Paisa can implement this feature) |
|    time     |                Transaction time                 |
|   remark    |                Transaction remark               |

**Comment by h4h13** [comment]
Hey, this requires to handle URLs which we don't want to do that and the motive of Paisa app is to add the records by user.
