### ISSUE TITLE
Costa Rican colon symbol is wrong.

### ISSUE THREAD

**Issue by Terkyz** [RetroMusicPlayer/Paisa#365]
The Costa Rican colon symbol is this (₡) but the app shows [this](https://files.catbox.moe/wuwhy3.jpg) missing icon symbol. Can anyone else confirm this problem? I think sometimes this can happen due to the device font (which in my case is the default Samsung) but the weird thing is that the symbol as I copy and paste it looks fine in any other app.

**Comment by h4h13** [comment]
Hey, this is because of font doesn't support some currency symbols so please change the font and check

**Comment by Terkyz** [comment]
I confirm, the default Paisa font does not support the Costa Rican colon in this case, by changing it to another font I can see the currency symbol.
