### ISSUE TITLE
Request for new account type: Online account

### ISSUE THREAD

**Issue by Terkyz** [RetroMusicPlayer/Paisa#366]
I have a Paypal account in dollars and my bank account is in my local currency, and maybe I am wrong but as far as I know in Paisa you cannot define different currencies for a user, so my request (if possible) is to define a type of online account with a different type of currency and I do not consider it necessary to make any conversion of local currency-currency online account.

When I say "online account" I am referring to sites like Paypal or Stripe that are not necessarily fully affiliated with my main bank account.

**Comment by h4h13** [comment]
Hey, we cannot implement anything online as the Paisa app motive was to keep everything local

**Comment by Terkyz** [comment]
Thanks for the answer. I wasn't referring to implementing Paypal itself, that would be a hell of a thing I would never suggest. I mean, within the "Add Account" menu there are three options: Cash, Bank and Wallet. My request was to add another "Online account" option.

Although, maybe according to what I'm saying, it would make more sense to have a "Custom account" button where you can modify your own account name and a currency type exclusive to that account, although the only problem I see with defining a different currency is that in the "Home" menu the other currency would not be seen.
