### ISSUE TITLE
The first letter of any text box is always capitalized.

### ISSUE THREAD

**Issue by Terkyz** [RetroMusicPlayer/Paisa#367]
I am not sure if this is a problem with my device, but I can assure you that it is not a keyboard problem because I have tried up to 3 different keyboards and they all suffer from the same problem, [which is that when typing in a text box the first letter always without exception is capitalized without reason](https://invideo-uploads-ap-south-1.s3.ap-south-1.amazonaws.com/45677e3f-7dc9-42df-bae6-05db7bc42bc1.mp4).

**Comment by h4h13** [comment]
Hey, this is fixed
