### ISSUE TITLE
Performance Issue : Home page slows down as number of transactions increase

### ISSUE THREAD

**Issue by vipulbehl** [RetroMusicPlayer/Paisa#378]
I migrated all my data from some other expense management app to Paisa. It had nearly 4000 transactions, after adding all the transactions the home screen lags and takes minutes to load the data. 

This problem only occurs on the home page, doesn't occur when I go to overview page and go to category expenses.

I am suspecting that since all the transactions are loaded onto the home page and there are graphs that are being loaded based on those transactions it might be leading to slow down.

**Comment by vipulbehl** [comment]
Actually this is slowing down add expense screen also, since it is an overlay on top of home screen add screen actions are also very slow (every swipe or any action has delay)

**Comment by h4h13** [comment]
Hey I have added a filter that will be home based on the account selected
