### ISSUE TITLE
Cannot open the app anymore 

### ISSUE THREAD

**Issue by Golem642** [RetroMusicPlayer/Paisa#388]
Since version 5.0.1, the app just stays stuck on startup (where it shows the app icon in big) and never makes it to the main menu, I cannot do anything now and my backup was from a while ago.
Please help !

**Comment by SiffatAhmed** [comment]
There's no such version. App is currently on 4.7.9 version.
![image](https://github.com/RetroMusicPlayer/Paisa/assets/54367251/84fe181d-1bd0-4739-87e9-0a293e6fc63c)

**Comment by Golem642** [comment]
![Screenshot_2023-11-19-00-00-58-921-edit_com.github.android.jpg](https://github.com/RetroMusicPlayer/Paisa/assets/65229557/7069b06c-b2dc-49a5-bd8a-ba87be99c0e5)

**Comment by d4f5409d** [comment]
I have serious problems with 5.0.4
![Screenshot_2023-11-19-09-08-19-16_4ca28f6827a5efdcf85a7e5ffee4dda7.jpg](https://github.com/RetroMusicPlayer/Paisa/assets/76624594/4c4466cd-571d-4aec-8ae0-0cfdc90c340f)

**Comment by Kurty00** [comment]
I also have issues with the app. It stays on the logo on startup since 5.0.1 through 5.0.4.

**Comment by h4h13** [comment]
Hey, these are internal track updates pushed to internal testing team and APK here in GitHub release

**Comment by h4h13** [comment]
I pushed a updated pls check if it's opening or not

**Comment by Kurty00** [comment]
It does not open with the new update.

**Comment by d4f5409d** [comment]
It works for me

**Comment by Golem642** [comment]
@h4h13 doesn't work for me too, still stuck
![Screenshot_2023-11-23-10-11-29-573_dev.hemanths.paisa.jpg](https://github.com/RetroMusicPlayer/Paisa/assets/65229557/0d9c419c-0401-4b70-b295-1c766a36939f)

**Comment by h4h13** [comment]
I don't know what's causing this problem can you clear the cache and open the all

**Comment by deavmi** [comment]
I am having this exact issue as well, #393

**Comment by Kurty00** [comment]
> I don't know what's causing this problem can you clear the cache and open the all

I already tried clearing the cache - that didn't lead to any improvement.

**Comment by Golem642** [comment]
> > I don't know what's causing this problem can you clear the cache and open the all
> 
> I already tried clearing the cache - that didn't lead to any improvement.

Same thing here, no cache is regenerating at all btw the only option i have left now is to erase all data which i definitely don't want to do

**Comment by deavmi** [comment]
> > > I don't know what's causing this problem can you clear the cache and open the all
> > 
> > 
> > I already tried clearing the cache - that didn't lead to any improvement.
> 
> Same thing here, no cache is regenerating at all btw the only option i have left now is to erase all data which i definitely don't want to do

There's gotta be someway to at least get out information out, whether it be a build of the app that dumps it immediately on startup. I have sent logs to the Telegram channel.

**Comment by Golem642** [comment]
@h4h13 is there any way you could revert back the code to 5.0.0 but publish it under a new version ? That way android would allow me to update the app (it doesn't want to downgrade) and we could backup our things before continuing to avoid any loss of data

**Comment by deavmi** [comment]
Also here is what I notice.
After clearing cache it shows logo of Paisa and stays there.

Then cache seems to be rebuilt, after that it no longer shows the logo but just a white screen.

**Comment by deavmi** [comment]
When it is on the white screen it seems the app responsiveness detector says the app is not responding so not sure if that helps drill down at where the issue could lie.

**Comment by deavmi** [comment]
> Since version 5.0.1, the app just stays stuck on startup (where it shows the app icon in big) and never makes it to the main menu, I cannot do anything now and my backup was from a while ago. Please help !

Having same issue :exclamation: :exclamation:

**Comment by Golem642** [comment]
How do we reopen this ?

**Comment by Golem642** [comment]
How do we reopen this ?

**Comment by deavmi** [comment]
Not sure. 

Dev needs to, it is a major issue.

On 25 November 2023 16:47:14 SAST, Golem64 ***@***.***> wrote:
>How do we reopen this ?
>
>-- 
>Reply to this email directly or view it on GitHub:
>https://github.com/RetroMusicPlayer/Paisa/issues/388#issuecomment-1826349937
>You are receiving this because you commented.
>
>Message ID: ***@***.***>

----
Tristan B. Velloza Kildaire

Web: https://deavmi.assigned.network
BNET IRC: deavmi
Email: ***@***.***

**Comment by Golem642** [comment]
> @h4h13 is there any way you could revert back the code to 5.0.0 but publish it under a new version ? That way android would allow me to update the app (it doesn't want to downgrade) and we could backup our things before continuing to avoid any loss of data

Also can you do this please ? It would be really useful. That way i can backup my data, and try the latest updates to see if it's fixed

**Comment by PrasannaVenkadesh** [comment]
> > @h4h13 is there any way you could revert back the code to 5.0.0 but publish it under a new version ? That way android would allow me to update the app (it doesn't want to downgrade) and we could backup our things before continuing to avoid any loss of data
> 
> Also can you do this please ? It would be really useful. That way i can backup my data, and try the latest updates to see if it's fixed

Here is how I downgraded to the last working version (4.9.3) without losing data.

1. Download [4.9.3 apk from releases](https://github.com/RetroMusicPlayer/Paisa/releases/download/v4.9.3/app-prod-release.apk) to your PC.
2. Enabled Developer Options & USB Debugging in your Phone.
3. Connect your phone with your PC. Run `adb devices` in your PC.
4. copy the downloaded apk to your phone. `adb push file-name.apk /data/local/tmp/`
5. `adb shell pm install -r -d /data/local/tmp/file-name.apk`

This should downgrade the app to 4.9.3


But @h4h13 the fix is needed for clean upgrade from 4.9.3 to 5.x, else we would be struck with 4.9.3 forever without a clean path to upgrade.
