### ISSUE TITLE
GoException: no routes for location: landing

### ISSUE THREAD

**Issue by Sagarparvizali** [RetroMusicPlayer/Paisa#391]
l encountered an issue with the app where I'm getting a "GoException: no routes for location: landing" error when opening it. Here are the details:
![Screenshot_2023-11-22-09-30-16-185_dev hemanths paisa](https://github.com/RetroMusicPlayer/Paisa/assets/25858168/cec4dd70-f0a9-4fdb-a048-d43ca241e535)

**Comment by FunkyFitzgerald** [comment]
Duplicate of #390

**Comment by h4h13** [comment]
Hey this is fixed
