### ISSUE TITLE
App goes to blank screen on startup

### ISSUE THREAD

**Issue by deavmi** [RetroMusicPlayer/Paisa#393]
Running latest version and it just stays on splash screen. I upgraded recently because older version was doing the same.

Cleared the cache, but it did not seem to help - not sure what is happening. All I can tell is that the app is slow when it does this, if I rotate my phone the time it takes before rotation is some time. Not sure if it is app related but it is normally never like that.

**Comment by deavmi** [comment]
![Screenshot_20231123-153825_LogFox.jpg](https://github.com/RetroMusicPlayer/Paisa/assets/5207740/a5fdbdc9-263f-467a-b305-75cdae969d23)

Not sure if thus helps?

**Comment by Kurty00** [comment]
Here is my log:

![Screenshot_20231124-190752.png](https://github.com/RetroMusicPlayer/Paisa/assets/24979920/6027e0c8-2b1a-45be-b27a-bc49632d2243)

![Screenshot_20231124-190815.png](https://github.com/RetroMusicPlayer/Paisa/assets/24979920/55014358-fcba-4ac7-87de-060395ce1c4b)

**Comment by deavmi** [comment]
> Here is my log:
> 
> ![Screenshot_20231124-190752.png](https://user-images.githubusercontent.com/24979920/285524375-6027e0c8-2b1a-45be-b27a-bc49632d2243.png) ![Screenshot_20231124-190815.png](https://user-images.githubusercontent.com/24979920/285524374-55014358-fcba-4ac7-87de-060395ce1c4b.png)
> 
> (@deavmi the log you send isn't filtered for the paisa app and didn't expand the lines)

Exact same issue. Something with Hive (I presume some DB) and some schema upgrade isn't working. I ended up resetting but it sucks ass. I wish the dev could just add some sort of DB dump as the first action, that would be so helpful.

**Comment by deavmi** [comment]
> Here is my log:
> 
> ![Screenshot_20231124-190752.png](https://user-images.githubusercontent.com/24979920/285524375-6027e0c8-2b1a-45be-b27a-bc49632d2243.png) ![Screenshot_20231124-190815.png](https://user-images.githubusercontent.com/24979920/285524374-55014358-fcba-4ac7-87de-060395ce1c4b.png)
> 
> (@deavmi the log you send isn't filtered for the paisa app and didn't expand the lines)

Nah, I filtered it for Paisa, but i just didn';t scroll up to the logs made on startup. Those were UI logs.

**Comment by deavmi** [comment]
But yes, I have the exact same issue. A type cast error which fails

**Comment by h4h13** [comment]
I think I got the issue resolved but need to test it can anyone please check this  [v5.0.8](https://github.com/RetroMusicPlayer/Paisa/releases/tag/v5.0.8)

**Comment by Kurty00** [comment]
Works for me

**Comment by coutnoah** [comment]
Issue seems resolved on my end. App can now open beyond the splash screen.

**Comment by deavmi** [comment]
Damn, I could have waited 😂😂😂

**Comment by deavmi** [comment]
Thanks
