### ISSUE TITLE
Any way to make the expense tab by default when we try to log a transaction? 

### ISSUE THREAD

**Issue by soorajsprakash** [RetroMusicPlayer/Paisa#406]
Any way to make the expense tab by default when we try to log a transaction? 

Currently, when we click on the "+" icon on the front screen, the "income" field is set by defaut.

We all know income comes only once a while, but the expenses are like daily, so is it possible to make "expenses" selected by default?
Or a settings page where we can select this?

Thanks

**Comment by h4h13** [comment]
This is handled as part of the new go_router_builder upgrade hence closing it sorry for not updating it
