### ISSUE TITLE
[Bug]Unable to select Country

### ISSUE THREAD

**Issue by Jean-BaptisteC** [RetroMusicPlayer/Paisa#41]
Pixel 6 - Android 13
version 3.0.4

I can search country but i can't select card under search bar (cards is grey)

Happy new year 🎉

**Comment by h4h13** [comment]
I'm able to do it, can you share screenshot or video of the problem

**Comment by qube-03** [comment]
this is whats happening: ![](https://i.imgur.com/ITUHGBW.png)

**Comment by mschahar** [comment]
Facing same issue....

**Comment by xmha97** [comment]
![Screenshot_2023-01-15-05-26-38-264_dev.hemanths.paisa.jpg](https://user-images.githubusercontent.com/23485114/212512898-5a3a6c5c-c173-4cc7-be29-fcc4b576183b.jpg)

**Comment by h4h13** [comment]
Fixed in upcoming update closing this
