### ISSUE TITLE
Outline not incompassing card

### ISSUE THREAD

**Issue by AbhinavParshad** [RetroMusicPlayer/Paisa#42]
Version 3.0.4
Android 13
Google Pixel 6

![Screenshot_20230110-204100](https://user-images.githubusercontent.com/104040204/211720059-44b10ff4-0759-48dc-ab44-ba625cf06dfd.png)

**Comment by h4h13** [comment]
For sec. I thought you were using iPhone 14, this is something I'm finding a solution
