### ISSUE TITLE
Add category groups or subcategories to Paisa

### ISSUE THREAD

**Issue by diasdmhub** [RetroMusicPlayer/Paisa#425]
I really liked the app, especially because it is easy to use and open source.

I find it useful to categorize some of my data with multiple categories.
One thing I wish Paisa had was the ability to create category groups or subcategories. Maybe a tagging system would help with this.

Because Budget is only set as a category property, I cannot separate or add some budgets I have. Therefore, I need to add several categories, one for each budget. It could be easier to manage the budget if these multiple category budgets could add up to a broader one.

For example, a recurring energy bill expense has a specific budget. This recurring expense could be included in the Energy category with its own budget and also in the Household category for a broader budget.

### Example:

| Category | Sub-category | Budget |
| --- | --- | --- |
| Household | Energy | 100 |
| - | Gas | 30 |

`Household budget = 130`

If possible, I think this addition could benefit Paisa and make it more flexible.

**Comment by h4h13** [comment]
This will be too much for Paisa to implement unless someone rescue it 😅
