### ISSUE TITLE
'Done' button under choose color section is cut off by Navigation bar.

### ISSUE THREAD

**Issue by ThisIsSidam** [RetroMusicPlayer/Paisa#429]
In devices still using the buttons to navigate, the navigation bar cuts off the 'Done' button under the 'Pick Color' section.

Please take a look at the attached image.  
![1708024160027](https://github.com/RetroMusicPlayer/Paisa/assets/96292204/50759ca9-d68a-4e8e-84f6-f580593bcaee)

Solution: The problem can be solved simply by increasing the height of the showModalBottomSheet.

**Comment by h4h13** [comment]
Hey, This is fixed in v6.0.3
