### ISSUE TITLE
Old Feature no longer available

### ISSUE THREAD

**Issue by bitcrafty** [RetroMusicPlayer/Paisa#431]
Hii, in the previous version, we were able to see individual entries in the overview section when we clicked on different categories. But now, it only shows a macro-overview of our entries (based on the selected filter) under different categories. So now if I want to check if I have executed a certain transaction or not, I have to scroll through so many entries to find the one (if it exists).

It would be great if we could just see each individual entry under different categories (with filter applied) when we click on them.

(P.S. I tried to create dummy data on a fresh install for visual example, but it doesn't let me go beyond entering your name. The next button isn't responding)

**Comment by h4h13** [comment]
Hey, Overview will be improved with graphs and other functionalities and it's been reworked from ground up
