### ISSUE TITLE
[Feature] Bring back the option to show a specific account in the home menu

### ISSUE THREAD

**Issue by Rafee-M** [RetroMusicPlayer/Paisa#436]
It's great that we can see all the accounts in one place in the home menu now, but I think it would be useful if we could also select specific accounts instead as well.

There could be a drop down menu here (shown below) to select the specific accounts to display:
![Screenshot_2024-03-02-11-39-33-38_4ca28f6827a5efdcf85a7e5ffee4dda7_1](https://github.com/RetroMusicPlayer/Paisa/assets/69535896/17de326d-b7e7-4fe7-81f4-0e09fca8a1f9)

**Comment by h4h13** [comment]
This was creating chaos in the app to maintain the state will bring back but for now will close the ticket
