### ISSUE TITLE
[Bug] Text in graph not visible

### ISSUE THREAD

**Issue by Rafee-M** [RetroMusicPlayer/Paisa#437]
### Issue 1:
If a bar is too high, the text box representing the value shows up too high and is not visible

**Possible solution:** Show the text box a little lower and to the side instead of above the bar in the graph.

### Issue 2:
The text in the Y-axis gets bugged out
1&2:
![InCollage_20240302_115902045](https://github.com/RetroMusicPlayer/Paisa/assets/69535896/31151f2c-9425-41f4-bf14-18c949f1db12)

### Improvement 1:
I think it might be better if Y-axis stays static when scrolling through them. Otherwise it's not possible to see it alongside other graphs

https://github.com/RetroMusicPlayer/Paisa/assets/69535896/74d2d332-d485-4554-8498-ca5b30de85de

**Comment by h4h13** [comment]
Hey, for now I don't have solution for it
