### ISSUE TITLE
[BUG] Cannot select the country in v3.0.4 

### ISSUE THREAD

**Issue by Atharv714** [RetroMusicPlayer/Paisa#44]
* During the initial setup, we are not able to choose the country 
* Thus the setup does not complete and app does not procede 

### Fix

* Download version 3.0.2
* Then download 3.0.4, and update the app, there will be no data lose

**Comment by Jean-BaptisteC** [comment]
Duplicate of #41

**Comment by h4h13** [comment]
Closing this as it will be fixed from next update
