### ISSUE TITLE
Regard home page =)total balance option

### ISSUE THREAD

**Issue by rizwaanimr** [RetroMusicPlayer/Paisa#442]
According to me most of the people use one account for most transactions and another for saving. So we do not need that saving account balance to be displayed in total balance..... we only need the account which we use for our spending to be displayed at the home page. According to the attachment screenshot below I want only Account A balance to be displayed in the total balance in the home page not the sum value of account balance of account A+B+C= total balance..... We want only Account A balance to be displayed.

In other money manager apps there is a switch menu in the account update page saying exclude the account from the total balance if you switch this on in account B and C you will be able to view only A balance in the home page.....same way of they want A and B balance to be displayed in the home page they will go in to account B's update account page  and  un switch the option the option called exclude the account from the total balance so that in the home page it will display sum balance of account A and B

Kindly please consider I love this app a lot but at the moment I'm using only one bank account details to avoid the confusion.
![Screenshot_2024-03-05-17-12-38-06_4ca28f6827a5efdcf85a7e5ffee4dda7](https://github.com/RetroMusicPlayer/Paisa/assets/69741521/fee8d61b-5483-41a6-998e-f71a5cb48f7c)
![Screenshot_2024-03-05-17-12-45-31_4ca28f6827a5efdcf85a7e5ffee4dda7](https://github.com/RetroMusicPlayer/Paisa/assets/69741521/7e86dedc-9785-4e06-8e00-e3060e103ddd)

**Comment by h4h13** [comment]
Duplicate #267 
This is already fixed
