### ISSUE TITLE
[Request] Please add option to change view type of accounts.  ie. list view 

### ISSUE THREAD

**Issue by mschahar** [RetroMusicPlayer/Paisa#45]

**Comment by h4h13** [comment]
The upcoming design will have a peak of the next account like this from picture

![Uploading Screenshot_1674143849.png…]()

**Comment by mschahar** [comment]
is it possible to add sneak peak view of accounts before detailed view? adding screenshot of ivy wallet for reference.   ![Screenshot_20230119_213732_Ivy Wallet.jpg](https://user-images.githubusercontent.com/85066622/213493151-270bf170-13c0-4058-9191-a6a3a5952141.jpg)

**Comment by h4h13** [comment]
Will add something like this but right now i can't think of design that goes well with Paisa app

**Comment by h4h13** [comment]
Closing this issue
