### ISSUE TITLE
[SUGGESTION] Add the project to crowdin

### ISSUE THREAD

**Issue by alpha4041** [RetroMusicPlayer/Paisa#47]
It would be better if the app was localized, please add the project to crowdin or weblate and implement a language selector.

**Comment by h4h13** [comment]
Will add this soon once it's kinda stable

**Comment by BobH-Official** [comment]
crowdin? weblate is also a good choice

**Comment by BobH-Official** [comment]
And one suggestion for Chinese
There are two "variants" of it, Simplified / Traditional.
We can just translate one of them( my suggestion is Simplified, because it is used by most of population) and use [openCC](https://github.com/BYVoid/OpenCC) to automatically transfer into another.

**Comment by h4h13** [comment]
IDK this supported crowdin for now we're doing manal
