### ISSUE TITLE
The EUR currency shouldn't have only Austria EUR in the title.

### ISSUE THREAD

**Issue by alpha4041** [RetroMusicPlayer/Paisa#48]
The EUR currency is titled "Austria Euro", but it should be found searching other european countries that use the EUR currency, and it should be titled European EUR.
I also think that the currency selector should be named "Select currency" instead of "Select country" as people (like me) probably search the country name and not the currency (that can be used by multiple countries)
![photo_2023-01-15_19-37-48](https://user-images.githubusercontent.com/88579269/212560432-e0bfaa33-bc6f-49d5-9cf4-15d9f0a4c778.jpg)

**Comment by h4h13** [comment]
Fixed text problem, but Austria Euro is €1 for this symbol right?

**Comment by alpha4041** [comment]
> Fixed text problem, but Austria Euro is €1 for this symbol right?

€ is the currency symbol for any country that uses euros.

**Comment by h4h13** [comment]
For now closing this issue.
