### ISSUE TITLE
[BUG] The expense and income value input text field is bugged.

### ISSUE THREAD

**Issue by alpha4041** [RetroMusicPlayer/Paisa#49]
The expense and icome value input text field is very bugged. I tried 3 things as in the video below:

1. Writing a large value like 5712 then deleting 712 and writing 5,12. The expense would still count as 5712
2. Creating an expense of 5,12 €. The app shows an expense of 5,00€
3. Tried modifying the last expense putting a point after the 5 (didn't work as the point wasn't entered) and then updating the 5 as 5,123 (didn't work as it still showed 5,00€)
4. Updating the same expense writing 5,125.66. It showed 5125 as like it ignored the ".66"

https://drive.proton.me/urls/FW7K2MSCB0#FgxZxQZBn7v4

**Comment by h4h13** [comment]
This will be fixed in next update
