### ISSUE TITLE
[Tablet] Can't select country

### ISSUE THREAD

**Issue by 0uros** [RetroMusicPlayer/Paisa#50]
![Screenshot_20230118_174201_Paisa](https://user-images.githubusercontent.com/67289586/213291090-704b2d3d-c1c1-4862-971d-89fec3f27b44.jpg)

This happen in 3.0.4 version.

**Comment by 0uros** [comment]
For some reason I downloaded the latest published version and it didn't work at all, the post says it's 3.0.5 but I downloaded 3.0.4, capable of being an error?

I downloaded the previous release and it works correctly, it lacks polishing details, but it helps me write things down.

**Comment by venkat2305** [comment]
I have the same issue
![Screenshot_2023-01-19-19-53-27-081_dev.hemanths.paisa.jpg](https://user-images.githubusercontent.com/55329452/213470392-517b644c-a0f8-4823-980d-044bf9541426.jpg)

**Comment by h4h13** [comment]
I have updated in play store internally, and will update it here

**Comment by h4h13** [comment]
https://github.com/RetroMusicPlayer/Paisa/releases/tag/v.3.0.9
