### ISSUE TITLE
[Suggestion] add ARS currency and other stuff

### ISSUE THREAD

**Issue by 0uros** [RetroMusicPlayer/Paisa#51]
HI! I'm here to make the suggestion that more coins be added, such as the Argentine Peso (ARS). I also want to clarify what, unless it is for having chosen dollars, but it is not possible for me to write down very large amounts of expenses, I try to write the amount of 27.666,81 and the application only saves 2766, which is a bit of a nuisance. It would also be great to have the possibility to alternate on whether to use "," or "." according to the customs that one has in his region!

That's all :)

**Comment by h4h13** [comment]
This is new for me to understand.

1. You want to add amount 27(dot)666(coma)87?

**Comment by 0uros** [comment]
Yes, I think you can find more information about it through this [link](https://www.datacamp.com/tutorial/decimal-comma-or-decimal-point-a-googlevis-visualization), in several countries it is used.

**Comment by h4h13** [comment]
This is convention 26,666.81 when we mention number more than thusand

**Comment by h4h13** [comment]
If you're talking about recent update that's been rolled back

**Comment by 0uros** [comment]
> This is convention 26,666.81 when we mention a number more than thousand

Yes, my suggestion was because when I write a decimal, I usually add a comma, not a dot

**Comment by EzeKoren** [comment]
I just added the Argentine Peso on Pull Request #118 

Have a nice evening!
