### ISSUE TITLE
An option to edit for both 'Select account' and 'Select category'

### ISSUE THREAD

**Issue by tvnmguy** [RetroMusicPlayer/Paisa#55]
An option to give edit(button) in Add Expense page for both 'Select account' and 'Select category'

Before;
![IMG_20230120_164656.jpg](https://user-images.githubusercontent.com/116799295/213684496-f4bd22a4-f21e-4249-97cd-0e8daa2e4972.jpg)

After;
![IMG_20230120_164625.jpg](https://user-images.githubusercontent.com/116799295/213684540-701e174f-3d1e-44fe-8b22-9858dec3eaa7.jpg)

**Comment by h4h13** [comment]
Edit will do what showing list  of items and take action on them?

**Comment by h4h13** [comment]
You can edit edit date you can click on the icon to pick date

**Comment by h4h13** [comment]
Hey, closing this for now
