### ISSUE TITLE
Add "Iranian Rial"

### ISSUE THREAD

**Issue by xmha97** [RetroMusicPlayer/Paisa#57]
Hi,
Please add "Iranian Rial"
Symbol: ﷼
https://en.m.wikipedia.org/wiki/Iranian_rial

![Screenshot_2023-01-20-18-38-01-991_dev.hemanths.paisa.jpg](https://user-images.githubusercontent.com/23485114/213731796-30e9ad62-7b85-42e6-bff8-6b937483d2fa.jpg)

Thanks.

**Comment by h4h13** [comment]
Is this the one

![image](https://user-images.githubusercontent.com/2574895/213778605-fbc543ea-bfd9-448a-8166-35d86175ad66.png)

**Comment by xmha97** [comment]
> Is this the one

Yes

**Comment by h4h13** [comment]
That's one question but don't know how to fix for now

**Comment by MidNightCola** [comment]
hey there, thanks for the app it works wonders, just one problem with rial, and I wonted to show case one problem, rial doesn't have the concept of cent like in dollar, so the last 2 zero is unnecessary, and I hope you can make it show English numbers it is kind of weird to see persian symbols in the app 😅

thank you and I wish you the very best

**Comment by h4h13** [comment]
Hey, I don't know how to fix this as we pub ([here ](https://pub.dev/packages/intl)) to show currency it's handled by inbuilt

**Comment by xmha97** [comment]
Why you removed Iranian Rial?

![Screenshot_2023-06-28-23-14-10-134_dev hemanths paisa](https://github.com/RetroMusicPlayer/Paisa/assets/23485114/7d0cb1b9-5a04-4070-b918-8672e6a460ef)
