### ISSUE TITLE
versionCode not increased?

### ISSUE THREAD

**Issue by IzzySoft** [RetroMusicPlayer/Paisa#58]
`versionCode` of today's release (v3.1.1) is the same as that of the previous one: `31`. Can you please make sure that `versionCode` is increased with each new release? Otherwise there will be no update notification for folks having the previous version installed (as Android considers it to be the same version as installed on-device) and thus have difficulties updating.

Thanks in advance!

**Comment by h4h13** [comment]
How are you updating the app

**Comment by h4h13** [comment]
Will take care of from upcoming update

**Comment by IzzySoft** [comment]
Thanks! Btw, I'd have a nice [badge](https://gitlab.com/IzzyOnDroid/repo/#if-my-app-is-available-here-do-you-have-a-badge-i-can-use-to-link-to-it) you might wish to add as number 4 in your row next to platform, download, version and [link here](https://apt.izzysoft.de/fdroid/index/apk/dev.hemanths.paisa) (there's also a second one in the style of that Playstore badge often uses by projects publishing there, should you prefer that – but seeing you've used the other one for this as well, you probably prefer this):

[<img src="https://img.shields.io/endpoint?url=https://apt.izzysoft.de/fdroid/api/v1/shield/dev.hemanths.paisa">](https://apt.izzysoft.de/fdroid/index/apk/dev.hemanths.paisa)

Those using my repo and having your app installed are receiving notifications via their F-Droid client whenever a new release (with properly increased `versionCode`) became available :wink:

**Comment by IzzySoft** [comment]
> How are you updating the app

Oops, missed that one. Well, guess my previous comment gave you a hint already: my updater looks out for new tags and grabs the APK from there, which then goes into my repo. If `versionCode` was properly increased, those using your app via my repo will get a notification via their F-Droid client on-device, as it detected an APK in the repo index with a higher `versionCode` than the one installed. This of course only works if `versionCode` indeed **was** increased.
