### ISSUE TITLE
[Feature Request] migration from another app

### ISSUE THREAD

**Issue by venkat2305** [RetroMusicPlayer/Paisa#59]
I've been using another [app](https://play.google.com/store/apps/details?id=com.ithebk.expensemanager). This app can export my transactions as CSV and XLSX. it would be great if it could be imported to this app. It has many categories. There's a note section to each transaction which can have multiple entries. If needed I would be glad to share a dummy of the transaction file. Please look into this. It would help a lot of people who want to migrate to Paisa. Thanks

**Comment by h4h13** [comment]
Yes please do, we can look into it

**Comment by venkat2305** [comment]
[dummy transactions.xlsx](https://github.com/RetroMusicPlayer/Paisa/files/10481610/dummy.transactions.xlsx)

this is a dummy transactions file. look into it. 
thanks in advance

**Comment by W1zardK1ng** [comment]
Thanks for having this issue open, im waiting to see this feature implemented as i want to migrate to Paisa from [MoneyWallet](https://github.com/AndreAle94/moneywallet)
I see Paisa has also implemented backup but it will be great if both backup and restore are in CSV format.
If so we can use the same restore option to migrate from other apps and also to restore older Paisa backups.

**Comment by SoiledBrush** [comment]
Same, want to migrate from MoneyWallet, as it is no longer maintained.

**Comment by h4h13** [comment]
Hey we don't support any apps data import/ export as they use own encryption or something to crypt the files we can't read nor interested in implementing this hence closing

**Comment by venkat2305** [comment]
No, wait. I was talking about importing the .CSV file which has all the data. Please reopen and let's discuss  @h4h13

**Comment by h4h13** [comment]
Making export and import CSV files difficult

Making CSV files readable and importing is difficult we can export but not import

**Comment by venkat2305** [comment]
The issue is that we have been using other apps for years, it's really difficult to migrate all the data manually so i hoped you would figure something out to make the transition easier

**Comment by W1zardK1ng** [comment]
[My Expenses](https://github.com/mtotschnig/MyExpenses) app is having the csv import option, maybe worth checking the code but no pressure.

**Comment by h4h13** [comment]
Making export and import CSV files difficult

Making CSV files readable and importing is difficult we can export but not import

**Comment by venkat2305** [comment]
Can you keep this open? Someone might be interested to work on this
