### ISSUE TITLE
Can we have Singapore Dollar(SGD) Sign

### ISSUE THREAD

**Issue by BobH-Official** [RetroMusicPlayer/Paisa#61]
I am in Singapore. Can we have SDG sign SG$ in app? Thank you.

**Comment by h4h13** [comment]
Is this the one?
![image](https://user-images.githubusercontent.com/2574895/215248609-d80ab401-f755-43ea-b041-ff8d7e6c4af6.png)

**Comment by BobH-Official** [comment]
maybe S$

from wikipedia:
The Singapore dollar ([sign](https://en.wikipedia.org/wiki/Currency_sign): S$; [code](https://en.wikipedia.org/wiki/ISO_4217): SGD) is the official [currency](https://en.wikipedia.org/wiki/Currency) of the [Republic of Singapore](https://en.wikipedia.org/wiki/Republic_of_Singapore). It is divided into 100 [cents](https://en.wikipedia.org/wiki/Cent_(currency)). It is normally abbreviated with the [dollar sign](https://en.wikipedia.org/wiki/Dollar_sign) $, or S$ to distinguish it from other dollar-denominated currencies. The [Monetary Authority of Singapore](https://en.wikipedia.org/wiki/Monetary_Authority_of_Singapore) (MAS) issues the banknotes and coins of the Singapore dollar.

**Comment by h4h13** [comment]
![image](https://user-images.githubusercontent.com/2574895/215331348-bf22dc00-fdbc-4f2b-b66a-32cf3ab20fbb.png)

**Comment by h4h13** [comment]
In flutter $ only comes maybe it's doesn't have perticular support
