### ISSUE TITLE
Build for iOS, etc.?

### ISSUE THREAD

**Issue by BobH-Official** [RetroMusicPlayer/Paisa#65]
I noticed that the app is written in flutter. Is it possible to build it into iOS, Web, Desktop? ( I don't have a Mac, so I can not test it myself)

[Doesn't mean publishing on Apple's App Store, but if it is possible, that's better of course]

**Comment by h4h13** [comment]
It's possible but we're doing as free and AppStore 99$/year we  can't afford that for now maybe future once it's paid app

**Comment by venkat2305** [comment]
Damn 30 Percent cut and 100 dollars per year to list on their platform. Is 30 Percent not enough.
Another reason to hate apple

**Comment by Alonely0** [comment]
And no sideloading...

**Comment by h4h13** [comment]
So closing this issue

**Comment by h4h13** [comment]
Maybe in future once we earn anything from Paisa
