### ISSUE TITLE
Accounts filter for Home tab

### ISSUE THREAD

**Issue by Surendrajat** [RetroMusicPlayer/Paisa#66]
An option to make select accounts visible/invisible on Home screen will be nice.

**Comment by h4h13** [comment]
can you show us example

**Comment by Surendrajat** [comment]
Sure. For example, you have a main account and a savings account and you don't want savings related total, transactions etc. to come up on the dashboard (Home screen). A simple filter or account chooser will be helpful in that case.

**Comment by h4h13** [comment]
Hey, this feels like doesn't fit with Paisa app as we don't have anything denote the cards as Saving or Current etc so closing
