### ISSUE TITLE
Make Navigation Bar transparent

### ISSUE THREAD

**Issue by electr1fy0** [RetroMusicPlayer/Paisa#68]
Issue:
The navigation bar should be transparent instead of black.
I already reported it months ago on Telegram and it was supposed to be fixed.

Reference:
![Screenshot_20230203-201933](https://user-images.githubusercontent.com/87616300/216633266-78846f7f-499c-4274-8a93-e5e0d65fbf43.png)

Documentation:
https://developer.android.com/develop/ui/views/layout/edge-to-edge

**Comment by h4h13** [comment]
HI @electr1fy0 we're not working with Android, it's Flutter code it's kinda difficult to achieve

**Comment by Begarudev** [comment]
@h4h13 can you assign this issue to me I have fixed it just need have a pull request
