### ISSUE TITLE
Feature request: Total balance

### ISSUE THREAD

**Issue by deavmi** [RetroMusicPlayer/Paisa#69]
Would it be possible to have a total balance counter per account so I can see how much I have left to spend.

**Comment by deavmi** [comment]
Thank you

**Comment by deavmi** [comment]
I use this app a lot, heavily rely on it

**Comment by h4h13** [comment]
Can  you explain how balance works I'm trying to understand the user perspective

**Comment by GrubbyHorsefly** [comment]
Yes this would be fantastic. If you set an initial amount in the account set up, it should show the total current balance by adding or subtracting income/expenses from the initial amount. There should be an option to switch to total balance (initial amount + income - expenses) from change in balance (income - expenses) on the homepage.

**Comment by deavmi** [comment]
> Yes this would be fantastic. If you set an initial amount in the account set up, it should show the total current balance by adding or subtracting income/expenses from the initial amount. There should be an option to switch to total balance (initial amount + income - expenses) from change in balance (income - expenses) on the homepage.

Yes this is what I enviosined but on a per account basis.

**Comment by deavmi** [comment]
I see this has now been added with the new update. Great!

(Also the month income/expense is awesome)
