### ISSUE TITLE
Minor nitpicks with the UI

### ISSUE THREAD

**Issue by Alonely0** [RetroMusicPlayer/Paisa#72]
Hi, thanks for your work!

I have some nitpicks with the UI, which shouldn't be hard to fix.

First, the navbar is black, when it should blend in with the menu:
![Screenshot_20230221-233104~2](https://user-images.githubusercontent.com/59423215/220476753-30629a71-bc2d-4252-8ecf-037d90b0de2e.png)
Vs
![Screenshot_20230221-234047~2](https://user-images.githubusercontent.com/59423215/220476776-a7ec921d-b70d-4f1f-9687-0185e00d1571.png)

Second, the add button is very large in comparison to other material you apps, like material files:
![Screenshot_20230221-233104~3](https://user-images.githubusercontent.com/59423215/220477019-ac73a147-87ad-49d1-8c70-dceee3e52366.png)
Vs
![Screenshot_20230221-233255~2](https://user-images.githubusercontent.com/59423215/220477042-edf959bd-6ccf-46a5-9bcd-a83a5e7bba45.png)

I would also appreciate if you matched the add button's foreground color to material files. Here are my chips as a reference, if you grant me the favor:
![Screenshot_20230221-233458](https://user-images.githubusercontent.com/59423215/220477350-57a06c71-6773-432c-bf32-90662f94fb98.png)

**Comment by alexandru-ionut-balan** [comment]
I think the navbar was fixed or it happens only on certain devices because mine blends in as it should. I'm on 3.8.4


![Screenshot_20230325-131855_1](https://user-images.githubusercontent.com/113347266/227714535-4be176f8-7b93-48eb-a9f6-a108346f2a86.png)

**Comment by Alonely0** [comment]
Yes, it recently got solved, thanks @h4h13 !

**Comment by purveshxd** [comment]
I made the Floating Action Button regular size.
Should I make a pull request?

**Comment by h4h13** [comment]
@purveshxd this is meant to be like that
