### ISSUE TITLE
Bug with decimal places for Euro income and expenses greater than € 999

### ISSUE THREAD

**Issue by Bushbrand17** [RetroMusicPlayer/Paisa#74]
I use Paisa with €.

If I want to enter income or expenses greater than € 999, a dot is automatically added to the amount. But this leads to the fact that the amount is entered incorrectly and can not be corrected. For example, if I want to enter 2000 €, the app recognizes 2 €. It doesn't matter if I remove the decimal point or replace it with a comma (2,000.00 / 2,000.00 / 2,000 / 2000 -> They all don't work). The app always records only 2 €. 

Thus, I can not enter amounts that have more than 3 digits.

**Comment by augustohub** [comment]
The same happens with Brazilian Real (R$)

**Comment by h4h13** [comment]
This will be taken care of in upcoming updates
