### ISSUE TITLE
Bug when adding more than 4 digits

### ISSUE THREAD

**Issue by Spart-v6** [RetroMusicPlayer/Paisa#75]
So I installed this app yesterday and added my expense say 25,000. But only 2,500 was added. It doesn't count for more than 4 digits.

**Comment by Spart-v6** [comment]
> So I installed this app yesterday and added my expense say 25,000. But only 2,500 was added. It doesn't count for more than 4 digits.

I'm using (₹) rupee as my currency

**Comment by vip20** [comment]
I'm also facing the same I issue.

**Comment by subhashay** [comment]
Same issue here as well. The only work around is to remove the coma (that gets auto added after 4 digits).

**Comment by h4h13** [comment]
This will be taken care of in upcoming updates
