### ISSUE TITLE
Option to duplicate or clone a transanction

### ISSUE THREAD

**Issue by abskmj** [RetroMusicPlayer/Paisa#78]
An option to duplicate or clone a transaction to add a new one would be helpful.

**Comment by h4h13** [comment]
Copying existing transaction and modify is that what your asking?

**Comment by abskmj** [comment]
Yes

**Comment by abskmj** [comment]
Setting up a recurring expense doesn't work for me primarily because there is no frequency for these expenses. For example, I order groceries online. My category and payment mode is usually the same for all these transactions. Just the date and amount would change. And I don't have a set frequency for these transactions. I order whenever I need the grocery.
