### ISSUE TITLE
The navigation bar is light on dark mode

### ISSUE THREAD

**Issue by xmha97** [RetroMusicPlayer/Paisa#79]
The navigation bar is light on dark mode!

![Screenshot_2023-03-07-23-18-15-369_dev.hemanths.paisa.jpg](https://user-images.githubusercontent.com/23485114/223536806-42b35610-5025-4053-b642-72ee3f5bb646.jpg)

**Comment by h4h13** [comment]
Android version

**Comment by xmha97** [comment]
> Android version 

Android 13
Xiaomi 11T (MIUI 14)

**Comment by AvalancheBreakdown** [comment]
Same problem here, using MiUI 13 (Android 12)

**Comment by alba4k** [comment]
are you guys using the miui forced dark mode by any chance?

**Comment by AvalancheBreakdown** [comment]
Sorry for the late reply, 
all other material apps seem to be working just fine with the built in MiUI dark mode toggle.

I think an older version of MiUI had a "override forced-dark mode" but that toggle isn't available on the newer versions

![Screenshot_2023-04-05-08-53-56-709_com simplemobiletools contacts pro](https://user-images.githubusercontent.com/102347046/229974194-6e582fa0-cab2-4821-9d06-6aabd58c2c7b.jpg)
![Screenshot_2023-04-05-08-54-02-188_com simplemobiletools contacts pro](https://user-images.githubusercontent.com/102347046/229974219-f78839f1-a779-4f41-b34a-7b77f6f9e96a.jpg)

**Comment by itsmmt305** [comment]
can confirm the navbar is light on dark mode
also why isnt it colored like with material you palette?

**Comment by SajalRG** [comment]
Hi, I'm able to reproduce this issue in  Pixel 2 API 32 emulator with GMS as well. Will try to check this issue.
