### ISSUE TITLE
[Suggested Enhancement] Planned/Scheduled expenses

### ISSUE THREAD

**Issue by ItamiWasTaken** [RetroMusicPlayer/Paisa#8]
put simply, a way to schedule an expense to repeat, similar to how you can do so with a calendar event.
![Screenshot_20220906-114453](https://user-images.githubusercontent.com/99271684/188678813-beb727ac-b3b0-4b01-960d-8642c02b11d2.png)
attached is a screenshot for reference to how the calendar works similarly to the suggestion

**Comment by h4h13** [comment]
This is something i need help in flutter it's difficult to implement
