### ISSUE TITLE
Multi-currency handling

### ISSUE THREAD

**Issue by Pkcarreno** [RetroMusicPlayer/Paisa#84]
There are countries that usually have more than one currency, or people who have accounts in different currencies, is my case.

but great app 👍

**Comment by h4h13** [comment]
Need more info and examples pls

**Comment by Pkcarreno** [comment]
hey @h4h13, sorry for not adding more context, I thought it was understood.

I mean the ability to add accounts that use a different currency than the main currency of the app.

**Comment by h4h13** [comment]
This will be difficult to do but I don't see a major user base on this
