### ISSUE TITLE
Currency request

### ISSUE THREAD

**Issue by HTaamas** [RetroMusicPlayer/Paisa#86]
I really want the hungarian currency in the app
Name : huf
The marking is : ft

**Comment by abiud254** [comment]
Yeah the app needs alot of currencies. I saw the app getting featured un a yourube video and immediately loved it inly to find out it's missing my currency as well.
It's Kenyan Shilling - ksh

**Comment by h4h13** [comment]
Which video from Youtube

**Comment by h4h13** [comment]
![image](https://user-images.githubusercontent.com/2574895/224406185-b04a319c-1cc4-4faf-b53a-33eec9be9c49.png)
Added wait for upcoming update

**Comment by abiud254** [comment]
> Which video from Youtube

Sam Beckman's Best Apps of the month video
