### ISSUE TITLE
Why does the app need internet access permission?

### ISSUE THREAD

**Issue by adarsh1001** [RetroMusicPlayer/Paisa#9]
First up, amazing work on the app! I have been on the hunt for a good expense tracker for a long time and this one really stands out: both UI-wise and feature-wise!

Regarding the issue, the app does have access to the internet but it isn't clear what it needs that for and what data points are being sent or are being planned to be sent in the near future. A critical application like an expense tracker can benefit from being completely offline since that would throw away all privacy concerns and we won't have to keep checking the source code after every update to see what has changed in the telemetry department. Is this something that we can look into for the Izzy/F-Droid flavor of the app at least?

**Comment by h4h13** [comment]
1. We're officially not publishing on F-Droid or any other platform only play store
2. We need internet for Google fonts to download
