### ISSUE TITLE
Add Romanian currency.

### ISSUE THREAD

**Issue by AlexFurdui** [RetroMusicPlayer/Paisa#93]
Hi! As Hemanth Savarala told me I'll put this request here. Thanks!

**Comment by h4h13** [comment]
![image](https://user-images.githubusercontent.com/2574895/224487152-21691ed9-c321-4e41-b2b9-68b4a5c18a44.png)
Is this works for RON currency?

**Comment by AlexFurdui** [comment]
> ![image](https://user-images.githubusercontent.com/2574895/224487152-21691ed9-c321-4e41-b2b9-68b4a5c18a44.png) Is this works for RON currency?

Hello, yes RON is the currency, thanks!
