### ISSUE TITLE
Feedback and feature requests for V3.4.7

### ISSUE THREAD

**Issue by joyskmathew** [RetroMusicPlayer/Paisa#94]
Small corrections:

1. Can you change the text "outcome" to "expense" in Homescreen card

2. Change the date format to either "day date month" or "date month day"

3. Change the currency name of Austrian Euro to just "Euro" as almost every EU countries also have Euro as their official currency 

Bugs found:

1. Debt and credit feature is not working at all. Once we add a debt/credit amount, we cannot repay the amount. I tried multiple times but not get reflecting in the transaction history

2. Search function not working properly 

Feature Request

1. Can you add the ability to upload the receipt for a transaction when we are entering the data

2. Widgets for quick glance of the income and expense and also the ability to quickly add both income and expense

3. Ability to add transactions in multiple currency, useful for those travelling to other countries. As of now, changing the currency, changes it globally

4. Ability to illustrate the income and expense data through line graph and pie chart. Line graph shows the increase/decrease trend while pie chart shows the categorical spending behaviour

**Comment by h4h13** [comment]
Small corrections:

Can you change the text "outcome" to "expense" in the Home screen card : Done

Change the date format to either "day date month" or "date month day" : Done 
![image](https://user-images.githubusercontent.com/2574895/224486585-567bc588-0ec3-44b5-ac18-dd04654a9542.png)


Change the currency name of the Austrian Euro to just "Euro" as almost every EU countries also have Euro as their official currency
But people prefer their country name with Euro init

**Comment by h4h13** [comment]
Feature Request

Can you add the ability to upload the receipt for a transaction when we are entering the data : **Need to create a different card** 

Widgets for quick glance of the income and expense and also the ability to quickly add both income and expense : **Flutter doesn't support Home screen widget yet** 

Ability to add transactions in multiple currency, useful for those travelling to other countries. As of now, changing the currency, changes it globally : This IDK

Ability to illustrate the income and expense data through line graph and pie chart. Line graph shows the increase/decrease trend while pie chart shows the categorical spending behaviour: I have milestones for graphs still need to learn

**Comment by yaomtc** [comment]
> Can you add the ability to upload the receipt for a transaction when we are entering the data : **Need to create a different card**

What does this mean?

I would like to attach an image but Paisa doesn't seem to support this currently.
