### ISSUE TITLE
Issues and Feature Requests

### ISSUE THREAD

**Issue by anishkn04** [RetroMusicPlayer/Paisa#96]
**Bug:**
1. If we type anything in capital letters, it instantly shows "Nothing found".
2. The search feature neither shows any results nor any error whenever searching for something.

**Request:**
1. Since I can't search for anything I'm not sure, but if it's not implemented please add a Total Remaining Balance (Or something like that) whenever I search for any item.

2. I shouldn't be criticizing but I think a smaller "+" button would be visually appealing.

**Comment by h4h13** [comment]
Bug: 
If you're relating to a search this is fixed wait for the update 
Request: 
1. I didn't get you 
2. Small is something common in all it's unique thing
