### ISSUE TITLE
Bug found in v3.4.8

### ISSUE THREAD

**Issue by jistro** [RetroMusicPlayer/Paisa#97]
The accounts section displays in each account the sum of the expenses and income combined

**Comment by h4h13** [comment]
That's the balance right?

**Comment by jistro** [comment]
> That's the balance right?

Yes, is the balance for each account. I'm using a bank and a cash account

**Comment by h4h13** [comment]
So what is the problem each account will have initial amount + total expenses + total income

**Comment by jistro** [comment]
> So what is the problem?
> each account will have an initial amount + total expenses + total income 

Apparently the accounts showed more than I had, I had to create new accounts to see my correct balance and everything was back to normal

**Comment by h4h13** [comment]
Are these fixed if not open an new issue
